#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate notices from the locked Windows dependency graph; no license text is invented."""
import json
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parents[1]
metadata = json.loads(subprocess.check_output([
    "cargo", "metadata", "--manifest-path", str(root / "Cargo.toml"), "--locked",
    "--format-version", "1", "--filter-platform", "x86_64-pc-windows-msvc",
]))
sections = ["flowmux Windows Rust dependency notices\nGenerated by scripts/rust-notices.py from Cargo.lock.\n"]
for package in sorted(metadata["packages"], key=lambda item: (item["name"], item["version"])):
    if package["source"] is None:
        continue  # flowmux's GPL license is installed separately.
    directory = Path(package["manifest_path"]).parent
    files = sorted(path for path in directory.iterdir() if path.is_file()
                   and path.name.lower().startswith(("license", "copying", "notice", "copyright")))
    if not files and package["name"].startswith("webview2-com"):
        files = [root / "assets/licenses/webview2-rs-MIT.txt"]
    if not files:
        raise RuntimeError(f"Missing upstream license: {package['name']} {package['version']}")
    sections.append(f"\n{'=' * 72}\n{package['name']} {package['version']}\n"
                    f"Declared license: {package['license']}\nRepository: {package['repository']}\n")
    for path in files:
        sections.append(f"\n{path.name}\n{path.read_text(encoding='utf-8')}\n")
for path in sorted((root / "assets/licenses").glob("Microsoft-WebView2-*.txt")):
    sections.append(f"\n{'=' * 72}\nMicrosoft WebView2 SDK 1.0.3650.58: {path.name}\n"
                    + path.read_text(encoding="utf-8-sig"))
sections.append("\n" + "=" * 72 + "\nMicrosoft.Windows.Console.ConPTY 1.24.260710001\n"
                + (root / "assets/licenses/Microsoft-ConPTY-LICENSE.txt").read_text(encoding="utf-8-sig"))
(root / "assets/THIRD_PARTY_RUST.txt").write_text("".join(sections), encoding="utf-8")
