# SPDX-License-Identifier: GPL-3.0-or-later
# Own hidden windows and an isolated loopback Git sshd; run under run-check.ps1 with a 100s cap.
param([string]$BuildDirectory="$PSScriptRoot\..\target\x86_64-pc-windows-msvc\debug",[Alias('Host')][string]$SshHost='',[int]$Port=22,[string]$IdentityFile='',[string]$ConfigFile='',[string]$RemoteDirectory='',[switch]$Tmux,[switch]$Ports)
$ErrorActionPreference='Stop'
$OutputEncoding=[Console]::OutputEncoding=New-Object Text.UTF8Encoding($false)
$BuildDirectory=(Resolve-Path $BuildDirectory).Path;$gui=Join-Path $BuildDirectory 'flowmux.exe';$cli=Join-Path $BuildDirectory 'flowmuxctl.exe'
Add-Type -ReferencedAssemblies System.Drawing -Path (Join-Path $PSScriptRoot 'ChromeFixture.cs')
Add-Type -Path (Join-Path $PSScriptRoot 'CliProbe.cs'),(Join-Path $PSScriptRoot 'EditorFixture.cs'),(Join-Path $PSScriptRoot 'OptionsFixture.cs'),(Join-Path $PSScriptRoot 'FindFixture.cs'),(Join-Path $PSScriptRoot 'PaneToolsFixture.cs')
$base=if($env:FLOWMUX_TEST_ARTIFACT_ROOT){$env:FLOWMUX_TEST_ARTIFACT_ROOT}else{[IO.Path]::GetTempPath()}
$directory=Join-Path $base ('ssh-한글-한-'+[guid]::NewGuid());[IO.Directory]::CreateDirectory($directory)|Out-Null
$fixture=New-Object EditorFixture($directory);$clock=[Diagnostics.Stopwatch]::StartNew();$hostProcess=$null;$server=$null;$out=$null;$err=$null;$serverOut=$null;$serverErr=$null;$pipeName=$null;$cleanup=$false;$failure=$null;$checks=0;$proofMarkers=@{};$tmuxSessions=@();$httpFixture=$null
$diagnostic=[ordered]@{mode='owned-hidden-real-SSH';physicalInput=$false;physicalIme=$false;checks=@();lastTree=$null}
function Require([bool]$Value,[string]$Message){if(-not $Value){throw $Message}}
function Same([string]$A,[string]$B){return [string]::Equals($A,$B,[StringComparison]::Ordinal)}
function Budget([int]$Max=5000){if($cleanup){return $Max};$left=90000-$clock.ElapsedMilliseconds;Require ($left -gt 0) 'SSH check exceeded 90 seconds';return [int][Math]::Min($Max,$left)}
function Passed([string]$Name){$script:checks++;$diagnostic.checks+=,$Name}
function Run([string]$File,[string[]]$Arguments,[int]$Exit=0,[int]$Max=5000){
 $diagnostic.lastCommand=@{file=$File;arguments=$Arguments};$p=[CliProbe]::Start($File,$Arguments,$directory,$directory);$o=$p.StandardOutput.ReadToEndAsync();$e=$p.StandardError.ReadToEndAsync()
 try{Require ($p.WaitForExit((Budget $Max))) ('Owned process deadline: '+$File+' '+($Arguments -join ' '));Require ($o.Wait(500)-and $e.Wait(500)) 'Owned output pipes did not close';$stdout=[CliProbe]::Output($o);$stderr=[CliProbe]::Output($e);Require ($p.ExitCode -eq $Exit) ('Unexpected exit '+$p.ExitCode+': '+$stderr+' '+$stdout);if($Exit){return $stderr};return $stdout}
 finally{if(-not $p.HasExited){$p.Kill();[CliProbe]::WaitAfterKill($p)};$p.Dispose()}
}
function Request([string[]]$Arguments,[int]$Exit=0,[int]$Max=5000){Require ([bool]$pipeName) 'Explicit owned pipe required';return ((Run $cli (@('--pipe',$pipeName,'--json')+$Arguments) $Exit $Max)|ConvertFrom-Json)}
function Tree([int]$Max=5000){$t=Request @('tree') 0 $Max;Require ($t.background_testing) 'Hidden debug host required';[ChromeFixture]::Size([long]$t.window_handle,$hostProcess.Id)|Out-Null;$diagnostic.lastTree=$t;return $t}
function Await([scriptblock]$Condition){$watch=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$watch.ElapsedMilliseconds;Require ($left -ge 100) 'SSH condition exceeded five seconds';$t=Tree ([int]$left);if(& $Condition $t){return $t};Start-Sleep -Milliseconds 20}while($true)}
function Stable($Tree,$Before){foreach($s in $Before){$n=@($Tree.surfaces|Where-Object {$_.id -ceq $s.id});Require ($n.Count -eq 1 -and $n[0].pid -eq $s.pid -and $n[0].view_handle -eq $s.view_handle -and $n[0].running) 'SSH UI replaced an existing terminal PID or WebView'}}
function Start-Host([string[]]$Arguments,[bool]$AllowDisconnected=$false){
 $utc=[DateTime]::UtcNow;$timer=[Diagnostics.Stopwatch]::StartNew();$script:pipeName=$null;$script:hostProcess=[CliProbe]::Start($gui,$Arguments,$directory,$directory);$script:out=$hostProcess.StandardOutput.ReadToEndAsync();$script:err=$hostProcess.StandardError.ReadToEndAsync();$recordPath=Join-Path $env:LOCALAPPDATA "flowmux\windows\instances\$($hostProcess.Id).json"
 do{Budget|Out-Null;Require (-not $hostProcess.HasExited -and $timer.ElapsedMilliseconds -lt 8000) 'Hidden SSH host startup exceeded eight seconds';if((Test-Path $recordPath)-and (Get-Item $recordPath).LastWriteTimeUtc -ge $utc){$r=Get-Content -Raw $recordPath|ConvertFrom-Json;Require ($r.pid -eq $hostProcess.Id) 'Wrong host discovery PID';$script:pipeName=$r.pipe;break};Start-Sleep -Milliseconds 20}while($true)
 return Await {param($t) @($t.surfaces).Count -gt 0 -and @($t.surfaces|Where-Object {-not $_.ready -or (-not $AllowDisconnected -and (-not $_.running -or -not $_.pid))}).Count -eq 0}
}
function Stop-Host{
 Request @('quit','--discard-state')|Out-Null;Require ($hostProcess.WaitForExit((Budget 5000))) 'Hidden host quit exceeded five seconds';Require ($hostProcess.ExitCode -eq 0) 'Hidden host exit failed';Require ($out.Wait(500)-and $err.Wait(500)) 'Host pipes did not close';$hostProcess.Dispose();$script:hostProcess=$null;$script:pipeName=$null
}
function Open-Dialog{
 $t=Tree;$buttons=@($t.chrome.controls|Where-Object {$_.kind -ceq 'workspace_header' -and $_.layout_visible});Require ($buttons.Count -eq 1) 'Missing workspace creation button';[OptionsFixture]::Click([long]$t.window_handle,[long]$buttons[0].handle,$hostProcess.Id)
 $t=Await {param($v) $v.tab_menu.kind -ceq 'creation'};$menu=$t.tab_menu.menu;$rows=@($menu.rows|Where-Object {$_.label -ceq 'New SSH Workspace'});Require ($rows.Count -eq 1 -and $rows[0].enabled) 'New SSH Workspace is unavailable';[OptionsFixture]::ClickMenu([long]$menu.window,[long]$rows[0].window,$hostProcess.Id)
 $t=Await {param($v) $v.ssh_dialog -and -not $v.tab_menu};return $t.ssh_dialog
}

function Color-Hex([long]$Color){return ('#{0:x2}{1:x2}{2:x2}' -f ($Color -band 255),(($Color -shr 8) -band 255),(($Color -shr 16) -band 255))}
function Dialog-Presentation($Panel,[bool]$PaintError=$false){
 $cues=@('Host alias or user@hostname','/srv/project (optional)','Optional','From SSH config (default 22)','Optional local key path','Optional; defaults to ~/.ssh/config')
 for($index=0;$index -lt $cues.Count;$index++){Require ([OptionsFixture]::Parent([long]$Panel.fields[$index].input,$hostProcess.Id) -eq $Panel.window -and $null -ne $Panel.fields[$index].cue -and (Same $Panel.fields[$index].cue $cues[$index])) ('Native SSH cue banner differs at field '+$index)}
 $size=[ChromeFixture]::Size([long]$Panel.window,$hostProcess.Id);$scale=[OptionsFixture]::Describe([long]$Panel.window,$hostProcess.Id).Dpi/96.0;$connect=[OptionsFixture]::RelativeBounds([long]$Panel.window,[long]$Panel.connect,$hostProcess.Id);$errorRect=[OptionsFixture]::RelativeBounds([long]$Panel.window,[long]$Panel.error_handle,$hostProcess.Id)
 Require ([Math]::Abs($connect.X-16*$scale) -le 1 -and [Math]::Abs($size[0]-$connect.X-$connect.Width-16*$scale) -le 1 -and [Math]::Abs($connect.Height-36*$scale) -le 1 -and [Math]::Abs($size[1]-$connect.Y-$connect.Height-16*$scale) -le 1) 'SSH Connect is not the full-width 36-DIP primary action with 16-DIP margins'
 Require ([Math]::Abs($size[1]-540*$scale) -le 1) 'SSH dialog client retains unused vertical space'
 Require ($errorRect.X -ge 0 -and $errorRect.Width -gt 0 -and $errorRect.Height -gt 0 -and $errorRect.X+$errorRect.Width -le $size[0] -and $errorRect.Y+$errorRect.Height -le $connect.Y) 'SSH inline error overlaps Connect or leaves its client bounds'
 foreach($handle in @($Panel.fields|ForEach-Object {$_.input})+@($Panel.tmux,$Panel.hint)){$r=[OptionsFixture]::RelativeBounds([long]$Panel.window,[long]$handle,$hostProcess.Id);Require ($r.Y+$r.Height -le $errorRect.Y) 'SSH form content overlaps its inline error'}
 if(-not $PaintError){return}
 Require ($Panel.error -and (Same ([OptionsFixture]::Text([long]$Panel.error_handle,$hostProcess.Id)) $Panel.error)) 'SSH validation error is not displayed in its actual HWND'
 $path=Join-Path $directory 'ssh-dialog.bmp';$capture=Request @('chrome-capture',$path);Require ($capture.root_handle -eq $Panel.window -and $capture.subtree) 'SSH dialog capture used the wrong owned production subtree'
 $inside=[ChromeFixture]::Pixel($path,($connect.X+4),($connect.Y+4));Require ($inside -ceq (Color-Hex $Panel.colors.connect_background) -and [ChromeFixture]::ColorCount($path,$connect.X,$connect.Y,$connect.Width,$connect.Height,(Color-Hex $Panel.colors.connect_foreground)) -gt 5) 'SSH Connect production painter omitted the accent background or contrasting text'
 Require ([ChromeFixture]::ColorCount($path,$errorRect.X,$errorRect.Y,$errorRect.Width,$errorRect.Height,(Color-Hex $Panel.colors.error)) -gt 5) 'SSH inline error production painter omitted its error color'
 Remove-Item -LiteralPath $path -Force
}
function Field($Panel,[string]$Key){$row=@($Panel.fields|Where-Object {$_.key -ceq $Key});Require ($row.Count -eq 1) ('Missing SSH field '+$Key);return [long]$row[0].input}
function Fill($Panel,[hashtable]$Values){foreach($key in $Values.Keys){[OptionsFixture]::SetText([long]$Panel.window,(Field $Panel $key),$hostProcess.Id,[string]$Values[$key])}}
function Submit($Panel){[OptionsFixture]::ClickMenu([long]$Panel.window,[long]$Panel.connect,$hostProcess.Id)}
function Reject($Panel,$Before,[hashtable]$Values){Fill $Panel $Values;Submit $Panel;$t=Await {param($v) $v.ssh_dialog.id -ceq $Panel.id -and $v.ssh_dialog.error -and -not $v.ssh_dialog.pending};Require (@($t.workspaces).Count -eq 1 -and @($t.surfaces).Count -eq 1) 'Invalid SSH form created a workspace';foreach($key in $Values.Keys){Require (Same ([OptionsFixture]::Text((Field $Panel $key),$hostProcess.Id)) ([string]$Values[$key])) ('Validation changed raw '+$key)};Stable $t $Before;return $t}
function Posix([string]$Path){Require ($Path -match '^[A-Za-z]:\\') 'Fixture requires a local Windows drive path';return '/'+$Path.Substring(0,1).ToLowerInvariant()+$Path.Substring(2).Replace('\','/')}
function Write-Utf8([string]$Path,[string[]]$Lines){[IO.File]::WriteAllLines($Path,$Lines,(New-Object Text.UTF8Encoding($false)))}
function Configure-Server{
 $git=Join-Path $env:ProgramFiles 'Git\usr\bin';$sshd=Join-Path $git 'sshd.exe';$keygen=Join-Path $env:WINDIR 'System32\OpenSSH\ssh-keygen.exe';Require ((Test-Path $sshd)-and (Test-Path $keygen)) 'Actual SSH prerequisite missing: Git sshd and Windows OpenSSH keygen are required'
 $user=(Run (Join-Path $git 'id.exe') @('-un')).Trim();$hostKey=Join-Path $directory 'host-key';$script:IdentityFile=Join-Path $directory 'identity 한글 한';$script:ConfigFile=Join-Path $directory 'config 한글 한'
 Run $keygen @('-q','-t','ed25519','-f',$hostKey,'-N','')|Out-Null;Run $keygen @('-q','-t','ed25519','-f',$IdentityFile,'-N','')|Out-Null;[IO.File]::Copy($IdentityFile+'.pub',(Join-Path $directory 'authorized_keys'))
 $listener=New-Object Net.Sockets.TcpListener([Net.IPAddress]::Loopback,0);try{$listener.Start();$script:Port=$listener.LocalEndpoint.Port}finally{$listener.Stop()}
 $known=Join-Path $directory 'known_hosts';$global=Join-Path $directory 'global_known_hosts';$pub=([IO.File]::ReadAllText($hostKey+'.pub')).Trim().Split(' ');Write-Utf8 $known @('[127.0.0.1]:'+$Port+' '+$pub[0]+' '+$pub[1]);Write-Utf8 $global @()
 Write-Utf8 $ConfigFile @('Host *','  BatchMode yes','  IdentitiesOnly yes','  StrictHostKeyChecking yes','  ConnectTimeout 3',('  UserKnownHostsFile "'+$known.Replace('\','/')+'"'),('  GlobalKnownHostsFile "'+$global.Replace('\','/')+'"'))
 $serverConfig=Join-Path $directory 'sshd_config';Write-Utf8 $serverConfig @("Port $Port",'ListenAddress 127.0.0.1',('HostKey "'+(Posix $hostKey)+'"'),('PidFile "'+(Posix (Join-Path $directory 'sshd.pid'))+'"'),('AuthorizedKeysFile "'+(Posix (Join-Path $directory 'authorized_keys'))+'"'),'StrictModes no','PasswordAuthentication no','KbdInteractiveAuthentication no','PubkeyAuthentication yes','UseDNS no','LogLevel ERROR','PrintLastLog no','PrintMotd no',$(if($Ports){'AllowTcpForwarding yes'}else{'AllowTcpForwarding no'}),'X11Forwarding no')
 $script:server=[CliProbe]::Start($sshd,@('-D','-e','-f',(Posix $serverConfig)),$directory,$directory);$script:serverOut=$server.StandardOutput.ReadToEndAsync();$script:serverErr=$server.StandardError.ReadToEndAsync();$timer=[Diagnostics.Stopwatch]::StartNew();$listening=$false
 do{Require (-not $server.HasExited -and $timer.ElapsedMilliseconds -lt 4000) 'Owned loopback sshd did not listen within four seconds';$tcp=New-Object Net.Sockets.TcpClient;try{$task=$tcp.ConnectAsync('127.0.0.1',$Port);if($task.Wait(100)-and $tcp.Connected){$listening=$true}}catch{}finally{$tcp.Dispose()};if(-not $listening){Start-Sleep -Milliseconds 20}}until($listening)
 $script:SshHost=$user+'@127.0.0.1';$script:RemoteDirectory=Posix $fixture.Root
}
function Remote-Proof([string]$Surface,[string]$Pane,[string]$ExpectedDirectory=$RemoteDirectory){
 $prefix='SSH_'+[guid]::NewGuid().ToString('N').Substring(0,8)+' ';$unicode='한글 한 😀';$marker=$prefix+$unicode;$bytes=[Text.Encoding]::UTF8.GetBytes($prefix);$octal=($bytes|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join ''; $cwdMarker='CWD_'+[guid]::NewGuid().ToString('N')+':'
 # Neither expected full marker occurs in echoed command input.
 $cwdOctal=([Text.Encoding]::UTF8.GetBytes($cwdMarker)|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join ''
 Request @('focus-tab',$Surface)|Out-Null;Request @('send-keys',$Pane,('printf '''+$octal+'%s\n'' '''+$unicode+'''; printf '''+$cwdOctal+'%s\n'' "$PWD"'))|Out-Null;Request @('send-key','Enter','--pane',$Pane)|Out-Null
 $timer=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$timer.ElapsedMilliseconds;Require ($left -ge 100) 'Actual SSH remote marker/CWD exceeded five seconds';$screen=Request @('read-screen','--surface',$Surface) 0 ([int]$left);$diagnostic.lastScreen=$screen.text;$flat=$screen.text.Replace("`r",'').Replace("`n",'');if($flat.Contains($marker)-and $flat.Contains($cwdMarker+$ExpectedDirectory)){break};Start-Sleep -Milliseconds 20}while($true)
 $t=Tree;$s=@($t.surfaces|Where-Object {$_.id -ceq $Surface});Require ($s.Count -eq 1 -and $s[0].running -and $s[0].pid -and [IO.Path]::GetFileNameWithoutExtension($s[0].shell.program) -ieq 'ssh' -and (Same $s[0].remote_cwd $ExpectedDirectory)) 'Remote proof lacks a running OpenSSH ConPTY or exact remote directory';$script:proofMarkers[$Surface]=$marker;return $t
}
function Toolbar($Tree,[string]$Workspace,[string]$State){
 $bar=$Tree.ssh_toolbar;Require ($bar -and $bar.workspace -ceq $Workspace -and $bar.state -ceq $State) ('SSH toolbar has wrong workspace/state; expected '+$State)
 foreach($key in @('status','connect','disconnect','authentication','ports')){Require ([long]$bar.controls.$key -ne 0 -and [OptionsFixture]::Parent([long]$bar.controls.$key,$hostProcess.Id) -eq $Tree.window_handle) ('SSH toolbar control has wrong native owner: '+$key)}
 Require ([OptionsFixture]::Describe([long]$bar.controls.ports,$hostProcess.Id).Enabled) 'SSH Ports action is unavailable'
 $connect=[OptionsFixture]::Describe([long]$bar.controls.connect,$hostProcess.Id);$disconnect=[OptionsFixture]::Describe([long]$bar.controls.disconnect,$hostProcess.Id)
 if($State -ceq 'connected'){Require (-not $connect.Enabled -and $disconnect.Enabled) 'Connected SSH toolbar has wrong native action availability'}
 if($State -ceq 'disconnected'){Require ($connect.Enabled -and -not $disconnect.Enabled) 'Disconnected SSH toolbar has wrong native action availability'}
 $caption=[OptionsFixture]::Text([long]$bar.controls.status,$hostProcess.Id);Require ($caption.Contains($SshHost) -and $caption.Contains(' · '+$State)) 'Actual SSH status HWND omits its destination or connection state'
 $native=@([ChromeFixture]::Read([long]$Tree.window_handle,$hostProcess.Id));$size=[ChromeFixture]::Size([long]$Tree.window_handle,$hostProcess.Id);$rects=@()
 $tabs=@($Tree.chrome.controls|Where-Object {$_.kind -ceq 'tab' -and $_.layout_visible});Require ($tabs.Count -gt 0) 'SSH toolbar geometry requires a visible pane tab row';$tabTop=($tabs|ForEach-Object {$_.rect.y}|Measure-Object -Minimum).Minimum
 foreach($key in @('status','connect','disconnect','authentication','ports')){$actual=@($native|Where-Object {$_.Handle -eq [long]$bar.controls.$key});Require ($actual.Count -eq 1 -and $actual[0].Shown -and $actual[0].Font -ne 0) ('SSH toolbar native control is absent, hidden or lacks its font: '+$key);$r=$actual[0];Require ($r.Width -gt 0 -and $r.Height -gt 0 -and $r.X -ge $Tree.chrome.sidebar_actual_width -and $r.Y -ge 0 -and $r.X+$r.Width -le $size[0] -and $r.Y+$r.Height -le $size[1] -and $r.Y+$r.Height -le $tabTop) ('SSH toolbar escapes the client/sidebar or overlaps the pane tab row: '+$key);$rects+=,$r}
 for($i=0;$i -lt $rects.Count;$i++){for($j=$i+1;$j -lt $rects.Count;$j++){$a=$rects[$i];$b=$rects[$j];Require (-not ($a.X -lt $b.X+$b.Width -and $b.X -lt $a.X+$a.Width -and $a.Y -lt $b.Y+$b.Height -and $b.Y -lt $a.Y+$a.Height)) 'SSH toolbar controls overlap'}}
 return $bar
}
function Toolbar-Paint($Tree,$Bar){
 # Offscreen production STATIC/BUTTON painters only; no desktop or WebView capture.
 $path=Join-Path $directory 'ssh-toolbar.bmp';$capture=Request @('chrome-capture',$path);Require ($capture.root_handle -eq $Tree.window_handle -and -not $capture.subtree) 'SSH toolbar capture selected a different native root'
 $native=@([ChromeFixture]::Read([long]$Tree.window_handle,$hostProcess.Id))
 foreach($key in @('status','connect','disconnect','authentication','ports')){$r=@($native|Where-Object {$_.Handle -eq [long]$Bar.controls.$key})[0];$drawn=@($capture.controls|Where-Object {$_.handle -eq [long]$Bar.controls.$key});Require ($drawn.Count -eq 1 -and $drawn[0].x -eq $r.X -and $drawn[0].y -eq $r.Y -and $drawn[0].width -eq $r.Width -and $drawn[0].height -eq $r.Height) ('Actual SSH control was not included at its live bounds: '+$key);$x=$r.X+4;$y=$r.Y+4;$width=$r.Width-8;$height=$r.Height-8;Require ($width -gt 0 -and $height -gt 0 -and [ChromeFixture]::Pixel($path,$r.X,$r.Y) -ceq $capture.background -and [ChromeFixture]::ColorCount($path,$x,$y,$width,$height,$capture.background) -lt $width*$height-5) ('Production SSH native painter omitted control text: '+$key)}
 Remove-Item -LiteralPath $path -Force
}
function Retained-History([string]$Surface,[string]$Marker){
 Require ($Marker -and $Marker.Contains('한글 한 😀')) 'History assertion requires a previously acknowledged unique Unicode marker'
 $screen=Request @('read-screen','--surface',$Surface,'--recent');$flat=$screen.text.Replace("`r",'').Replace("`n",'');Require ($flat.Contains($Marker)) 'SSH disconnect/reconnect erased acknowledged Unicode terminal history'
}
function Check-Config($Tree,[string]$Workspace,[string]$Name,[bool]$ExpectedTmux=$false){$ws=@($Tree.workspaces|Where-Object {$_.id -ceq $Workspace});Require ($ws.Count -eq 1 -and $ws[0].ssh -and (Same $ws[0].name $Name) -and (Same $ws[0].ssh.cwd $RemoteDirectory) -and (Same $ws[0].ssh.target.identity_file $IdentityFile) -and (Same $ws[0].ssh.target.config_file $ConfigFile) -and $ws[0].ssh.target.port -eq $Port -and [bool]$ws[0].ssh.tmux -eq $ExpectedTmux) 'SSH config/name paths lost original Unicode or connection options';return $ws[0]}
function Tmux-Remote([string]$Command,[int]$Exit=0){
 $ssh=Join-Path $env:WINDIR 'System32\OpenSSH\ssh.exe';return (Run $ssh @('-T','-F',$ConfigFile,'-i',$IdentityFile,'-p',[string]$Port,'-o','BatchMode=yes','-o','IdentitiesOnly=yes','-o','StrictHostKeyChecking=yes','-o','ConnectTimeout=3',$SshHost,$Command) $Exit).Trim()
}
function Tmux-Session([string]$Surface){return 'flowmux-'+([guid]$Surface).ToString('N')}
function Tmux-Pid([string]$Session){$value=Tmux-Remote ('tmux display-message -p -t '''+$Session+''' ''#{pane_pid}''');Require ($value -match '^[1-9][0-9]*$') 'Real tmux did not report its remote pane PID';return $value}
function Tmux-Proof($Identity,[string]$Value,[string]$PanePid){
 $tag='TMUX_'+[guid]::NewGuid().ToString('N').Substring(0,8)+' 한글 한 😀:';$octal=([Text.Encoding]::UTF8.GetBytes($tag)|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join '';$expected=$tag+$Value+':'+$PanePid+':'+$RemoteDirectory
 Request @('focus-tab',$Identity.surface)|Out-Null;Request @('send-keys',$Identity.pane,('printf '''+$octal+'%s:%s:%s\n'' "$FLOWMUX_TMUX_VERIFY" "$$" "$PWD"'))|Out-Null;Request @('send-key','Enter','--surface',$Identity.surface)|Out-Null
 $timer=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$timer.ElapsedMilliseconds;Require ($left -ge 100) 'Actual tmux shell state proof exceeded five seconds';$screen=Request @('read-screen','--surface',$Identity.surface,'--recent') 0 ([int]$left);$diagnostic.tmuxScreen=$screen;if($screen.text.Replace("`r",'').Replace("`n",'').Contains($expected)){break};Start-Sleep -Milliseconds 20}while($true)
}
function Invoke-TmuxCase{
 Require ($SshHost -and $IdentityFile -and $ConfigFile -and $RemoteDirectory.StartsWith('/') -and $Port -ge 1 -and $Port -le 65535) '-Tmux requires an explicit real SSH fixture Host, Port, IdentityFile, pinned ConfigFile and RemoteDirectory'
 $version=Tmux-Remote 'tmux -V';Require ($version -match '^tmux ') 'The explicit SSH fixture has no real tmux'
 $tree=Start-Host @('--shell=cmd','--cwd',$fixture.Root);$local=Request @('identify');$original=@($tree.surfaces);$panel=Open-Dialog;$name='tmux 한글 한 😀'
 Fill $panel @{host=$SshHost;cwd=$RemoteDirectory;name=$name;port=[string]$Port;identity=$IdentityFile;config=$ConfigFile};[OptionsFixture]::SetChecked([long]$panel.window,[long]$panel.tmux,$hostProcess.Id,$true);$tree=Tree;Require ($tree.ssh_dialog.tmux_checked) 'Native tmux checkbox was not checked';Submit $panel
 $tree=Await {param($t) -not $t.ssh_dialog -and @($t.surfaces).Count -eq 2 -and @($t.surfaces|Where-Object {-not $_.ready -or -not $_.running}).Count -eq 0};$remote=Request @('identify');$ws=Check-Config $tree $remote.workspace $name $true;$session=Tmux-Session $remote.surface;$script:tmuxSessions+=,$session
 Require ($ws.root.content.surfaces[0].kind.type -ceq 'ssh_terminal' -and $ws.root.content.surfaces[0].kind.tmux_session -ceq $session) 'Initial tmux session name does not belong to the created surface'
 $tree=Await {param($t) $t.ssh_toolbar.state -ceq 'connected'};$panePid=Tmux-Pid $session;$value=[guid]::NewGuid().ToString('N');Request @('send-keys',$remote.pane,('FLOWMUX_TMUX_VERIFY='+$value))|Out-Null;Request @('send-key','Enter','--surface',$remote.surface)|Out-Null;Tmux-Proof $remote $value $panePid;Stable (Tree) $original;Passed 'tmux-native-create-real-remote-shell-PID-Unicode-marker-and-state'
 $tree=Tree;$sshBefore=@($tree.surfaces|Where-Object {$_.id -ceq $remote.surface})[0];$bar=Toolbar $tree $remote.workspace 'connected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.disconnect,$hostProcess.Id)
 $tree=Await {param($t) $t.ssh_toolbar.state -ceq 'disconnected' -and @($t.surfaces|Where-Object {$_.id -ceq $remote.surface -and $_.resources_released -and -not $_.running}).Count -eq 1};Tmux-Remote ('tmux has-session -t '''+$session+'''')|Out-Null;Require ((Tmux-Pid $session) -ceq $panePid) 'Disconnect replaced or terminated the actual remote tmux pane'
 Request @('new-tab')|Out-Null;$offline=Request @('identify');$offlineSession=Tmux-Session $offline.surface;$script:tmuxSessions+=,$offlineSession;$tree=Tree;Require ($offline.workspace -ceq $remote.workspace -and @($tree.surfaces).Count -eq 3 -and @($tree.surfaces|Where-Object {$_.id -cne $local.surface -and $_.running}).Count -eq 0) 'Offline tmux tab spawned before Connect';Tmux-Remote ('tmux has-session -t '''+$offlineSession+'''') 1|Out-Null
 $bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id);$tree=Await {param($t) $t.ssh_toolbar.state -ceq 'connected' -and @($t.surfaces|Where-Object {-not $_.ready -or -not $_.running}).Count -eq 0};Stable $tree $original
 $sshAfter=@($tree.surfaces|Where-Object {$_.id -ceq $remote.surface})[0];Require ($sshAfter.pid -ne $sshBefore.pid -and $sshAfter.view_handle -eq $sshBefore.view_handle -and $sshAfter.holder.window -eq $sshBefore.holder.window -and (Tmux-Pid $session) -ceq $panePid) 'Reconnect replaced a retained view or remote tmux process';Tmux-Proof $remote $value $panePid;$offlinePid=Tmux-Pid $offlineSession;Require ($offlinePid -cne $panePid) 'First offline-tab launch did not create a separate tmux pane';Passed 'tmux-disconnect-retains-state-reconnect-attaches-and-offline-tab-first-start-creates'
 Request @('focus-tab',$remote.surface)|Out-Null;$tree=Tree;$bar=Toolbar $tree $remote.workspace 'connected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.disconnect,$hostProcess.Id);$tree=Await {param($t) $t.ssh_toolbar.state -ceq 'disconnected' -and @($t.surfaces|Where-Object {$_.id -cne $local.surface -and $_.running}).Count -eq 0}
 $saved=Request @('save-state');Stop-Host;$tree=Start-Host @('--restore-window',$saved.window) $true;Check-Config $tree $remote.workspace $name $true|Out-Null;Require (@($tree.surfaces).Count -eq 3 -and @($tree.surfaces|Where-Object {$_.id -in @($remote.surface,$offline.surface) -and -not $_.running}).Count -eq 2) 'Restored tmux tabs changed IDs or auto-connected'
 Request @('focus-tab',$remote.surface)|Out-Null;$tree=Tree;$bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id);$tree=Await {param($t) $t.ssh_toolbar.state -ceq 'connected'};Require ((Tmux-Pid $session) -ceq $panePid -and (Tmux-Pid $offlineSession) -ceq $offlinePid) 'Restore created new remote tmux panes';Tmux-Proof $remote $value $panePid;Passed 'tmux-save-restore-stays-disconnected-and-attaches-same-remote-state'
 $diagnostic.tmuxPhase='disconnect-after-restore';$tree=Tree;$bar=Toolbar $tree $remote.workspace 'connected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.disconnect,$hostProcess.Id);$tree=Await {param($t) $t.ssh_toolbar.state -ceq 'disconnected' -and @($t.surfaces|Where-Object {$_.id -cne $local.surface -and $_.running}).Count -eq 0}
 $diagnostic.tmuxPhase='attach-missing';Tmux-Remote ('tmux kill-session -t '''+$session+'''')|Out-Null;Tmux-Remote ('tmux has-session -t '''+$session+'''') 1|Out-Null;$before=@($tree.surfaces|Where-Object {$_.id -ceq $local.surface});$shape=$tree.workspaces|ConvertTo-Json -Depth 40 -Compress
 $bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id);$tree=Await {param($t) $t.ssh_toolbar.state -ceq 'failed' -and @($t.surfaces|Where-Object {$_.id -ceq $remote.surface -and -not $_.running -and $_.resources_released -and $_.exit_code -ne 0}).Count -eq 1};Toolbar $tree $remote.workspace 'failed'|Out-Null;Tmux-Remote ('tmux has-session -t '''+$session+'''') 1|Out-Null;Require ((Tmux-Pid $offlineSession) -ceq $offlinePid -and (Same ($tree.workspaces|ConvertTo-Json -Depth 40 -Compress) $shape)) 'Missing tmux session was recreated or changed retained layout';Stable $tree $before;Passed 'missing-remote-tmux-session-fails-attach-without-recreating-shell'
 Stop-Host
}
function Ports-Open([string]$Workspace){
 $t=Tree;Require ($t.ssh_toolbar.workspace -ceq $Workspace) 'Ports source workspace changed';[OptionsFixture]::ClickMenu([long]$t.window_handle,[long]$t.ssh_toolbar.controls.ports,$hostProcess.Id)
 return (Await {param($v) $v.ssh_ports.workspace -ceq $Workspace}).ssh_ports
}
function Ports-Fill($Panel,[string]$Remote,[string]$Local=''){
 [OptionsFixture]::SetText([long]$Panel.window,[long]$Panel.remote,$hostProcess.Id,$Remote);[OptionsFixture]::SetText([long]$Panel.window,[long]$Panel.local,$hostProcess.Id,$Local)
}
function Ports-Add($Panel,[int]$Remote,[string]$Local=''){
 $before=@((Tree).ssh_forwards.id);Ports-Fill $Panel ([string]$Remote) $Local;[OptionsFixture]::ClickMenu([long]$Panel.window,[long]$Panel.add,$hostProcess.Id)
 $t=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -notin $before}).Count -eq 1};$forward=@($t.ssh_forwards|Where-Object {$_.id -notin $before})[0];return $forward.id
}
function Ports-Row($Tree,[string]$Id){$rows=@($Tree.ssh_ports.rows|Where-Object {$_.id -ceq $Id});Require ($rows.Count -eq 1) 'Forward has no matching native row';return $rows[0]}
function Ports-Click($Tree,[string]$Id,[string]$Action){$row=Ports-Row $Tree $Id;[OptionsFixture]::ClickMenu([long]$Tree.ssh_ports.viewport,[long]$row.$Action,$hostProcess.Id)}
function Ports-Preview([string]$Id){
 $t=Tree;$target=@($t.ssh_forwards|Where-Object {$_.id -ceq $Id})[0];$expectedUrl='http://127.0.0.1:'+$target.port;Ports-Click $t $Id 'preview';$binding='flowmux-ssh-preview://'+$Id
 $t=Await {param($v) @($v.browsers|Where-Object {$_.preview_binding -ceq $binding -and -not $_.loading -and -not $_.preview_expired -and $_.url -in @($expectedUrl,($expectedUrl+'/'))}).Count -ge 1};$identity=Request @('identify');$browser=@($t.browsers|Where-Object {$_.id -ceq $identity.surface})
 Require ($browser.Count -eq 1 -and $browser[0].preview_binding -ceq $binding) 'Preview did not select its stable bound browser';$f=@($t.ssh_forwards|Where-Object {$_.id -ceq $Id})[0];Require ($browser[0].url -ceq ('http://127.0.0.1:'+$f.port+'/') -or $browser[0].url -ceq ('http://127.0.0.1:'+$f.port)) 'Preview did not navigate through its actual local listener'
 $dom=(Request @('browser','eval',('pane:'+$identity.pane),'document.querySelector("#label").textContent')).result;Require (Same $dom '첫째 한글 한 é 😀') 'Forwarded real HTTP DOM lost Unicode or did not reach remote service';return $browser[0]
}
function Ports-Layout($Tree){
 $p=$Tree.ssh_ports;$native=[OptionsFixture]::Describe([long]$p.window,$hostProcess.Id);$size=[ChromeFixture]::Size([long]$p.window,$hostProcess.Id)
 Require ($native.Owner -eq $Tree.window_handle -and $native.OwnerEnabled -and -not $p.native_visible -and $native.Title -ceq 'SSH Ports — local browser preview' -and [Math]::Abs($size[0]-480*$native.Dpi/96.0) -le 1) 'Ports is not the hidden 480-DIP modeless owned native window'
 $rects=@();foreach($key in @('viewport','remote','local','https','add','error_handle')){$r=[OptionsFixture]::RelativeBounds([long]$p.window,[long]$p.$key,$hostProcess.Id);Require ($r.Width -gt 0 -and $r.Height -gt 0 -and $r.X -ge 0 -and $r.Y -ge 0 -and $r.X+$r.Width -le $size[0] -and $r.Y+$r.Height -le $size[1]) ('Ports control escaped its native client: '+$key);$rects+=,$r}
 for($i=0;$i -lt $rects.Count;$i++){for($j=$i+1;$j -lt $rects.Count;$j++){$a=$rects[$i];$b=$rects[$j];Require (-not ($a.X -lt $b.X+$b.Width -and $b.X -lt $a.X+$a.Width -and $a.Y -lt $b.Y+$b.Height -and $b.Y -lt $a.Y+$a.Height)) 'Ports native controls overlap'}}
 Require ((Same ([OptionsFixture]::Text([long]$p.add,$hostProcess.Id)) 'Add forwarding') -and (Same ([OptionsFixture]::Text([long]$p.https,$hostProcess.Id)) 'HTTPS preview')) 'Ports native actions have wrong labels'
 foreach($row in $p.rows){$caption=[OptionsFixture]::Text([long]$row.label,$hostProcess.Id);Require ($caption.Contains('Remote '+$row.remote_port+' → local ') -and $caption.Contains($row.state)) 'Forward label omits its actual mapping or state';foreach($key in @('label','preview','remove')){Require ([OptionsFixture]::Parent([long]$row.$key,$hostProcess.Id) -eq $p.viewport) 'Forward row is owned by the wrong viewport'}}
}
function Invoke-PortsCase{
 Require (-not $SshHost) '-Ports uses its isolated Git sshd and loopback HTTP service; external servers are not supported by this branch'
 Add-Type -Path (Join-Path $PSScriptRoot 'BrowserFixture.cs');$script:httpFixture=New-Object BrowserFixture;$remotePort=([Uri]$httpFixture.Origin).Port;Configure-Server
 $tree=Start-Host @('--shell=cmd','--cwd',$fixture.Root);$local=Request @('identify');$panel=Open-Dialog;Fill $panel @{host=$SshHost;cwd=$RemoteDirectory;name='포트 한글 한';port=[string]$Port;identity=$IdentityFile;config=$ConfigFile};Submit $panel
 $tree=Await {param($v) -not $v.ssh_dialog -and @($v.surfaces).Count -eq 2 -and @($v.surfaces|Where-Object {-not $_.running -or -not $_.ready}).Count -eq 0};$remote=Request @('identify');$tree=Remote-Proof $remote.surface $remote.pane;$before=@($tree.surfaces);$panel=Ports-Open $remote.workspace;Ports-Layout (Tree)
 foreach($values in @(@{remote='0';local=''},@{remote='abc';local='123'},@{remote=[string]$remotePort;local='0'})){Ports-Fill $panel $values.remote $values.local;[OptionsFixture]::ClickMenu([long]$panel.window,[long]$panel.add,$hostProcess.Id);$tree=Await {param($v) $v.ssh_ports.error -and -not $v.ssh_ports.pending};Require (@($tree.ssh_forwards).Count -eq 0 -and (Same $tree.ssh_ports.remote_value $values.remote) -and (Same $tree.ssh_ports.local_value $values.local)) 'Invalid forwarding created a process or rewrote draft';Stable $tree $before}
 Passed 'ports-modeless-native-geometry-labels-and-invalid-port-draft-preservation'
 $auto=Ports-Add $panel $remotePort;$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $auto -and $_.state -ceq 'connected'}).Count -eq 1};$autoBefore=@($tree.ssh_forwards|Where-Object {$_.id -ceq $auto})[0]
 $reserve=New-Object Net.Sockets.TcpListener([Net.IPAddress]::Loopback,0);try{$reserve.Start();$fixedPort=$reserve.LocalEndpoint.Port}finally{$reserve.Stop()};$fixed=Ports-Add $tree.ssh_ports $remotePort ([string]$fixedPort)
 $tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.state -ceq 'connected'}).Count -eq 2};$fixedBefore=@($tree.ssh_forwards|Where-Object {$_.id -ceq $fixed})[0];Require ($fixedBefore.port -eq $fixedPort -and $autoBefore.port -ne $fixedPort) 'Requested fixed listener or independent automatic listener was not established';Ports-Layout $tree
 $preview=Ports-Preview $auto;$fixedPreview=Ports-Preview $fixed;Stable (Tree) $before;$saved=Request @('save-state');$state=[IO.File]::ReadAllText($saved.path,[Text.Encoding]::UTF8)|ConvertFrom-Json;$savedWorkspace=@($state.workspaces|Where-Object {$_.id -ceq $remote.workspace})[0];$savedJson=$savedWorkspace|ConvertTo-Json -Depth 50 -Compress
 Require (@($savedWorkspace.ssh.forwards).Count -eq 2 -and $savedJson.Contains('flowmux-ssh-preview://'+$auto) -and $savedJson.Contains('flowmux-ssh-preview://'+$fixed) -and -not $savedJson.Contains('http://127.0.0.1:')) 'Saved preview replaced its stable binding with a transient loopback URL';Passed 'automatic-fixed-listeners-real-forwarded-Unicode-DOM-and-stable-saved-preview-binding'
 # Real window.open keeps an opener relationship; revocation must destroy its child, not merely hide it.
 $previewContext=Request @('identify');Require ($previewContext.surface -ceq $fixedPreview.id) 'Popup source is not the fixed forwarding preview';$popupName='ports_'+[guid]::NewGuid().ToString('N');$popup=(Request @('browser','eval',('pane:'+$previewContext.pane),('window.portPopup=window.open(location.href,"'+$popupName+'");window.portPopup!==null'))).result;Require ($popup -eq $true) 'Forwarded preview did not return a real WindowProxy'
 $tree=Await {param($v) @($v.browsers|Where-Object {$_.popup_opener -ceq $fixedPreview.id -and -not $_.loading}).Count -eq 1 -and $v.popup.pending -eq 0};$popupChild=@($tree.browsers|Where-Object {$_.popup_opener -ceq $fixedPreview.id})[0];Require ($popupChild.preview_binding -ceq $fixedPreview.preview_binding -and $popupChild.preview_generation -ceq $fixedPreview.preview_generation) 'Preview popup lost its forwarding binding/generation';[OptionsFixture]::Describe([long]$popupChild.view_handle,$hostProcess.Id)|Out-Null;[OptionsFixture]::Describe([long]$popupChild.holder.window,$hostProcess.Id)|Out-Null
 $tree=Tree;$bar=Toolbar $tree $remote.workspace 'connected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.disconnect,$hostProcess.Id);$pids=@($autoBefore.pid,$fixedBefore.pid)
 $tree=Await {param($v) @($v.ssh_forwards).Count -eq 0 -and @(Get-Process -Id $pids -ErrorAction SilentlyContinue).Count -eq 0 -and @($v.browsers|Where-Object {$_.id -in @($preview.id,$fixedPreview.id) -and -not $_.preview_expired}).Count -eq 0 -and $v.ssh_toolbar.state -ceq 'disconnected'};Stable $tree @($before|Where-Object {$_.id -ceq $local.surface})
 Require (@($tree.browsers|Where-Object {$_.id -ceq $popupChild.id}).Count -eq 0 -and -not (($tree.workspaces|ConvertTo-Json -Depth 50 -Compress).Contains($popupChild.id)) -and [OptionsFixture]::WindowDestroyed([long]$popupChild.view_handle) -and [OptionsFixture]::WindowDestroyed([long]$popupChild.holder.window)) 'Disconnect retained the preview popup model, WebView or HWND'
 Request @('focus-tab',$fixedPreview.id)|Out-Null;$expiredContext=Request @('identify');$deniedEval=Request @('browser','eval',('pane:'+$expiredContext.pane),'document.title') 1;$deniedNavigate=Request @('browser','navigate',('pane:'+$expiredContext.pane),$fixedPreview.url) 1;Require ($deniedEval.error -match 'expired' -and $deniedNavigate.error -match 'expired') 'Expired preview still permits evaluation or navigation';$tree=Tree
 $bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id);$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.state -ceq 'connected'}).Count -eq 2 -and $v.ssh_toolbar.state -ceq 'connected'}
 $autoAfter=@($tree.ssh_forwards|Where-Object {$_.id -ceq $auto})[0];$fixedAfter=@($tree.ssh_forwards|Where-Object {$_.id -ceq $fixed})[0];Require ($autoAfter.surface -cne $autoBefore.surface -and $autoAfter.session -cne $autoBefore.session -and $fixedAfter.port -eq $fixedPort) 'Reconnect reused a retired forwarding generation or lost its fixed listener';$newPreview=Ports-Preview $auto;Ports-Preview $fixed|Out-Null;Remote-Proof $remote.surface $remote.pane|Out-Null;Passed 'disconnect-retires-owned-listeners-expires-previews-and-reconnect-opens-new-real-listeners'
 $tree=Tree;$terminals=@($tree.surfaces);Ports-Click $tree $auto 'remove';$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $auto}).Count -eq 0 -and @(Get-Process -Id $autoAfter.pid -ErrorAction SilentlyContinue).Count -eq 0 -and @($v.browsers|Where-Object {$_.preview_binding -ceq ('flowmux-ssh-preview://'+$auto) -and -not $_.preview_expired}).Count -eq 0}
 $retained=@($tree.ssh_forwards|Where-Object {$_.id -ceq $fixed})[0];Require ($retained.pid -eq $fixedAfter.pid -and $retained.state -ceq 'connected') 'Remove terminated an unrelated forwarding process';Require (@($tree.ssh_ports.rows|Where-Object {$_.id -ceq $auto}).Count -eq 0) 'Removed forwarding still has a native row';Stable $tree $terminals;Passed 'remove-only-selected-forwarding-process-and-expire-its-previews'
 # The HTTP fixture is a foreign listener relative to the SSH forward, kept alive throughout this collision.
 $collision=Ports-Add $tree.ssh_ports $remotePort ([string]$remotePort);$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $collision -and $_.state -ceq 'failed' -and $_.output_ended -and $_.output_sequence -gt 0 -and $_.parsed_sequence -eq $_.output_sequence}).Count -eq 1};$failed=@($tree.ssh_forwards|Where-Object {$_.id -ceq $collision})[0];Require ($failed.error -and -not (Ports-Row $tree $collision).local_port) 'Foreign listener was incorrectly accepted as a ready forward';Stable $tree $terminals
 $request=[Net.HttpWebRequest]::Create($httpFixture.Origin);$request.Timeout=1000;$request.ReadWriteTimeout=1000;$response=$request.GetResponse();try{$reader=New-Object IO.StreamReader($response.GetResponseStream(),[Text.Encoding]::UTF8);try{$page=$reader.ReadToEnd();Require ($page.Contains('첫째 한글 한 é 😀')) 'Collision damaged the unrelated listener'}finally{$reader.Dispose()}}finally{$response.Dispose()}
 [OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$tree.ssh_toolbar.controls.authentication,$hostProcess.Id);$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $collision -and $_.open}).Count -eq 1};$opened=@($tree.ssh_forwards|Where-Object {$_.id -ceq $collision})[0];$native=[OptionsFixture]::Describe([long]$opened.window,$hostProcess.Id);Require ($native.Owner -eq $tree.window_handle -and -not $opened.native_visible -and $opened.view_handle -eq $failed.view_handle -and $opened.output_sequence -eq $failed.output_sequence -and $opened.parsed_sequence -eq $failed.parsed_sequence) 'Authentication replaced the failed forwarding view or finalized output'
 [FindFixture]::PostClose([long]$opened.window,$hostProcess.Id);$tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $collision -and -not $_.open}).Count -eq 1};$closed=@($tree.ssh_forwards|Where-Object {$_.id -ceq $collision})[0];Require ($closed.window -eq $opened.window -and $closed.view_handle -eq $opened.view_handle -and $closed.output_sequence -eq $opened.output_sequence -and $closed.parsed_sequence -eq $opened.parsed_sequence) 'Closing Authentication destroyed its retained terminal/output';[OptionsFixture]::Describe([long]$closed.window,$hostProcess.Id)|Out-Null;Stable $tree $terminals;Passed 'foreign-listener-collision-fails-without-false-ready-and-authentication-close-retains-output-view'
 Ports-Click $tree $collision 'remove';$tree=Await {param($v) @($v.ssh_forwards).Count -eq 1 -and @($v.ssh_ports.rows).Count -eq 1};$fixedSpec=(@($tree.ssh_forwards|Where-Object {$_.id -ceq $fixed})[0].spec|ConvertTo-Json -Compress);$previewIds=@($tree.browsers|Where-Object {$_.preview_binding -in @(('flowmux-ssh-preview://'+$auto),('flowmux-ssh-preview://'+$fixed))}|ForEach-Object {$_.id});Require ($previewIds.Count -eq 2) 'Restore requires both retained fixed and orphan preview surfaces'
 $saved=Request @('save-state');Stop-Host;$tree=Start-Host @('--restore-window',$saved.window) $true
 $tree=Await {param($v) @($v.browsers|Where-Object {$_.id -in $previewIds -and $_.preview_expired}).Count -eq 2};Require (@($tree.ssh_forwards).Count -eq 0 -and @($tree.surfaces|Where-Object {$_.id -ceq $remote.surface -and -not $_.running -and -not $_.pid}).Count -eq 1) 'Restore automatically started SSH or forwarding'
 $restoredWs=@($tree.workspaces|Where-Object {$_.id -ceq $remote.workspace})[0];Require (@($restoredWs.ssh.forwards).Count -eq 1 -and (Same ($restoredWs.ssh.forwards[0]|ConvertTo-Json -Compress) $fixedSpec)) 'Restore changed the fixed specification or recreated a removed forwarding';$expiredFixed=@($tree.browsers|Where-Object {$_.id -ceq $fixedPreview.id})[0];Require ($expiredFixed.preview_expired) 'Restored fixed preview did not begin expired'
 Request @('focus-tab',$remote.surface)|Out-Null;$tree=Tree;$bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id)
 $tree=Await {param($v) @($v.ssh_forwards|Where-Object {$_.id -ceq $fixed -and $_.state -ceq 'connected'}).Count -eq 1 -and @($v.browsers|Where-Object {$_.id -ceq $fixedPreview.id -and -not $_.preview_expired -and -not $_.loading}).Count -eq 1};$restoredForward=@($tree.ssh_forwards|Where-Object {$_.id -ceq $fixed})[0];Require ($restoredForward.port -eq $fixedPort -and (Same ($restoredForward.spec|ConvertTo-Json -Compress) $fixedSpec)) 'Connect after restore changed the fixed forward specification/listener'
 Ports-Open $remote.workspace|Out-Null;$restoredPreview=Ports-Preview $fixed;Require ($restoredPreview.id -ceq $fixedPreview.id -and $restoredPreview.instance -cne $expiredFixed.instance) 'Restored fixed preview changed Surface ID or reused its expired WebView';$tree=Tree;Require (@($tree.ssh_forwards).Count -eq 1 -and @($tree.browsers|Where-Object {$_.id -ceq $preview.id -and $_.preview_expired -and $_.preview_binding -ceq ('flowmux-ssh-preview://'+$auto)}).Count -eq 1) 'Connecting restored fixed forwarding revived or removed the orphaned preview';Passed 'actual-host-restore-remains-disconnected-then-reopens-fixed-Unicode-preview-with-stable-ID-and-keeps-orphan-expired'
 Stop-Host
}

try{
 $doctor=(Run $cli @('doctor'))|ConvertFrom-Json;Require ($doctor.status -ceq 'ok' -and $doctor.background_testing) 'A hidden debug SSH build is required'
 Require (-not ($Tmux -and $Ports)) 'Choose either -Tmux or -Ports'
 if($Ports){Invoke-PortsCase}elseif($Tmux){Invoke-TmuxCase}else{
 if(-not $SshHost){Configure-Server}else{Require ($IdentityFile -and $ConfigFile -and $RemoteDirectory.StartsWith('/')) 'External fixture requires identity, pinned noninteractive config and absolute remote directory'}
 $tree=Start-Host @('--shell=cmd','--cwd',$fixture.Root);$original=@($tree.surfaces);$local=Request @('identify');$panel=Open-Dialog;$native=[OptionsFixture]::Describe([long]$panel.window,$hostProcess.Id)
 Require ($panel.owner -eq $tree.window_handle -and $native.Owner -eq $tree.window_handle -and $native.Enabled -and -not $native.OwnerEnabled -and -not $panel.native_visible -and [Math]::Abs(([ChromeFixture]::Size([long]$panel.window,$hostProcess.Id))[0]-460*$native.Dpi/96.0) -le 1) 'SSH dialog is not the hidden owned modal with a 460-DIP client'
 Require ((@($panel.fields.label)-join '|') -ceq 'Host|Remote directory|Workspace name|Port|Identity file|SSH config file' -and @($panel.fields).Count -eq 6) 'SSH dialog field structure differs from Linux';Dialog-Presentation $panel
 $bottom=0;$size=[ChromeFixture]::Size([long]$panel.window,$hostProcess.Id);foreach($row in $panel.fields){$b=[OptionsFixture]::RelativeBounds([long]$panel.window,[long]$row.input,$hostProcess.Id);Require ($b.Y -ge $bottom -and $b.X -ge 0 -and $b.X+$b.Width -le $size[0] -and $b.Y+$b.Height -le $size[1]) 'SSH input leaves its panel or overlaps another field';$bottom=$b.Y+$b.Height}
 $name='원격 한글 한 é 😀';Reject $panel $original @{host='-oProxyCommand=invalid';name=$name}|Out-Null;Reject $panel $original @{host=$SshHost;port='0';name=$name}|Out-Null;$invalid=Reject $panel $original @{port=[string]$Port;cwd='C:\not-posix';name=$name};Dialog-Presentation $invalid.ssh_dialog $true;Passed 'owned-six-native-cues-primary-button-error-paint-and-invalid-input-preserve-Unicode-and-existing-PID'
 Fill $panel @{host=$SshHost;cwd=$RemoteDirectory;name=$name;port=[string]$Port;identity=$IdentityFile;config=$ConfigFile};$input=Field $panel 'host'
 [OptionsFixture]::CompositionGuard([long]$panel.window,$input,$hostProcess.Id,$true);[OptionsFixture]::PostEnter($input,$hostProcess.Id);$tree=Tree;Require ($tree.ssh_dialog.id -ceq $panel.id -and $tree.ssh_dialog.composing -and @($tree.workspaces).Count -eq 1) 'Composing Enter submitted SSH';[OptionsFixture]::CompositionGuard([long]$panel.window,$input,$hostProcess.Id,$false)
 [OptionsFixture]::KeyMessage($input,$hostProcess.Id,229,0,$false,$false,$false,$false);[OptionsFixture]::PostEnter($input,$hostProcess.Id);$tree=Tree;Require ($tree.ssh_dialog.id -ceq $panel.id -and @($tree.workspaces).Count -eq 1) 'PROCESS/229 Enter submitted SSH'
 [OptionsFixture]::KeyMessage($input,$hostProcess.Id,229,0,$true,$false,$false,$false);[OptionsFixture]::PostKey($input,$hostProcess.Id,13,$false,$true);[OptionsFixture]::PostKey($input,$hostProcess.Id,13,$true,$false);$tree=Tree;Require ($tree.ssh_dialog.id -ceq $panel.id -and @($tree.workspaces).Count -eq 1) 'Repeated Enter submitted SSH';Stable $tree $original
 [FindFixture]::PostClose([long]$panel.window,$hostProcess.Id);$tree=Await {param($t) -not $t.ssh_dialog};Require ([OptionsFixture]::Describe([long]$tree.window_handle,$hostProcess.Id).Enabled) 'Closing SSH form left owner disabled';Stable $tree $original;Passed 'owned-composition-PROCESS-repeat-guards-and-window-close-cancel'
 $panel=Open-Dialog;Fill $panel @{host=$SshHost;cwd=$RemoteDirectory;name=$name;port=[string]$Port;identity=$IdentityFile;config=$ConfigFile};Submit $panel
 $tree=Await {param($t) -not $t.ssh_dialog -and @($t.workspaces).Count -eq 2 -and @($t.surfaces).Count -eq 2 -and @($t.surfaces|Where-Object {-not $_.ready -or -not $_.running}).Count -eq 0};$remote=Request @('identify');Check-Config $tree $remote.workspace $name|Out-Null;$tree=Remote-Proof $remote.surface $remote.pane;Stable $tree $original;Passed 'native-Connect-starts-real-SSH-ConPTY-with-remote-Unicode-and-CWD-output'
 $changedDirectory=$RemoteDirectory
 if($server){
  $changed=Join-Path $fixture.Root '이동 한';[IO.Directory]::CreateDirectory($changed)|Out-Null;$changedDirectory=Posix $changed
  $encoded=($changedDirectory.Split('/')|ForEach-Object {[Uri]::EscapeDataString($_)}) -join '/'
  Request @('send-keys',$remote.pane,('cd '''+$changedDirectory+'''; printf ''\033]7;%s\007'' ''file://flowmux-check'+$encoded+''''))|Out-Null;Request @('send-key','Enter','--pane',$remote.pane)|Out-Null
  Await {param($t) @($t.surfaces|Where-Object {$_.id -ceq $remote.surface -and (Same $_.remote_cwd $changedDirectory)}).Count -eq 1}|Out-Null
  Remote-Proof $remote.surface $remote.pane $changedDirectory|Out-Null
 }
 Request @('new-tab')|Out-Null;$tab=Request @('identify');Require ($tab.workspace -ceq $remote.workspace -and $tab.pane -ceq $remote.pane -and $tab.surface -cne $remote.surface) 'SSH new-tab lost workspace or pane';Remote-Proof $tab.surface $tab.pane $changedDirectory|Out-Null
 Request @('split','vertical')|Out-Null;$split=Request @('identify');Require ($split.workspace -ceq $remote.workspace -and $split.pane -cne $tab.pane) 'SSH split lost workspace or failed to split';$tree=Remote-Proof $split.surface $split.pane $changedDirectory;Require (@($tree.surfaces.pid|Select-Object -Unique).Count -eq 4) 'SSH tabs did not receive distinct processes';Stable $tree $original;Passed 'new-tab-and-split-reuse-SSH-config-and-execute-in-exact-remote-CWD'
 $before=@($tree.surfaces);$shape=$tree.workspaces|ConvertTo-Json -Depth 40 -Compress;$rejected=Request @('move-tab',$remote.surface,'--to-pane',$local.pane) 1;Require ([bool]$rejected.error) 'Moving SSH tab into local workspace was accepted';$detached=Request @('detach-tab',$remote.surface) 1;Require ([bool]$detached.error) 'Detaching an SSH tab was accepted';$tree=Tree;Require (@($tree.detached_windows).Count -eq 0) 'Rejected SSH tear-out created a detached window';Require (Same ($tree.workspaces|ConvertTo-Json -Depth 40 -Compress) $shape) 'Rejected SSH/local move or tear-out mutated topology';Stable $tree $before;Passed 'SSH-local-workspace-move-rejected-without-session-loss'
 # Disconnect stops every SSH session in this workspace without replacing its retained views.
 Request @('focus-tab',$split.surface)|Out-Null;$tree=Await {param($t) $t.ssh_toolbar.workspace -ceq $remote.workspace -and $t.ssh_toolbar.state -ceq 'connected'};$bar=Toolbar $tree $remote.workspace 'connected';Toolbar-Paint $tree $bar
 $sshBefore=@($tree.surfaces|Where-Object {$_.id -in @($remote.surface,$tab.surface,$split.surface)});Require ($sshBefore.Count -eq 3) 'Reconnect requires three real SSH sessions';$oldPids=@($sshBefore.pid);$history=@{};foreach($s in $sshBefore){$history[$s.id]=$proofMarkers[$s.id];Retained-History $s.id $history[$s.id]}
 $workspaceBefore=@($tree.workspaces|Where-Object {$_.id -ceq $remote.workspace})[0];$shape=$workspaceBefore.root|ConvertTo-Json -Depth 40 -Compress
 # Leave real remote application modes active while a bounded remote sleep prevents prompt resets.
 $altMarker='SSH_ALT_'+[guid]::NewGuid().ToString('N').Substring(0,8);$altOctal=([Text.Encoding]::UTF8.GetBytes($altMarker)|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join ''
 Request @('send-keys',$split.pane,('printf ''\033[?1h\033[?2004h\033[?1049h\033[H\033[2J'+$altOctal+'\n''; sleep 30'))|Out-Null;Request @('send-key','Enter','--surface',$split.surface)|Out-Null
 $modeWait=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$modeWait.ElapsedMilliseconds;Require ($left -ge 100) 'Remote application-mode setup exceeded five seconds';$modeBefore=Request @('read-screen','--surface',$split.surface,'--recent') 0 ([int]$left);if($modeBefore.screen.buffer -ceq 'alternate' -and $modeBefore.text.Contains($altMarker)){break};Start-Sleep -Milliseconds 20}while($true)
 $diagnostic.inputModesBefore=@{surface=$split.surface;screen=$modeBefore.screen;alternateMarker=$altMarker}
 $cursorBefore=Request @('send-key','Enter','--surface',$split.surface);$diagnostic.inputModesBefore.cursor=$cursorBefore;Require ($cursorBefore.ok -and $cursorBefore.surface -ceq $split.surface -and $cursorBefore.application_cursor -eq $true -and $cursorBefore.accepted_bytes -eq 1 -and $cursorBefore.delivery -ceq 'queued') 'Remote DECSET 1 did not enable actual application cursor mode'
 $modeText='모드 한 😀';$pasteBefore=Request @('paste','--surface',$split.surface,'--',$modeText);$diagnostic.inputModesBefore.paste=$pasteBefore;Require ($pasteBefore.surface -ceq $split.surface -and $pasteBefore.bracketed -eq $true -and $pasteBefore.accepted_bytes -eq ([Text.Encoding]::UTF8.GetByteCount($modeText)+12) -and $pasteBefore.delivery -ceq 'queued') 'Remote DECSET 2004 did not enable actual bracketed paste'
 [OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.disconnect,$hostProcess.Id)
 $tree=Await {param($t) $t.ssh_toolbar.state -ceq 'disconnected' -and @($t.surfaces|Where-Object {$_.id -in @($remote.surface,$tab.surface,$split.surface) -and $_.running}).Count -eq 0 -and @(Get-Process -Id $oldPids -ErrorAction SilentlyContinue).Count -eq 0};$bar=Toolbar $tree $remote.workspace 'disconnected';Stable $tree $original
 $workspaceAfter=@($tree.workspaces|Where-Object {$_.id -ceq $remote.workspace})[0];Require (Same ($workspaceAfter.root|ConvertTo-Json -Depth 40 -Compress) $shape) 'Disconnect changed pane/tab identities or remote CWD'
 foreach($s in $sshBefore){$now=@($tree.surfaces|Where-Object {$_.id -ceq $s.id});Require ($now.Count -eq 1 -and $now[0].view_handle -eq $s.view_handle -and $now[0].holder.window -eq $s.holder.window -and (Same $now[0].remote_cwd $changedDirectory)) 'Disconnect replaced a retained SSH view, holder or CWD';if($s.id -cne $split.surface){Retained-History $s.id $history[$s.id]}}
 Request @('new-tab')|Out-Null;$offline=Request @('identify');$tree=Tree;Require ($offline.workspace -ceq $remote.workspace -and $offline.pane -ceq $split.pane -and @($tree.surfaces).Count -eq 5 -and @($tree.surfaces|Where-Object {$_.id -cne $local.surface -and $_.running}).Count -eq 0) 'Creating a disconnected SSH tab spawned a connection or changed its source';Toolbar $tree $remote.workspace 'disconnected'|Out-Null;Stable $tree $original
 Passed 'native-toolbar-caption-geometry-paint-Disconnect-stops-SSH-PIDs-preserves-local-history-and-offline-new-tab'
 $bar=$tree.ssh_toolbar;[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id)
 $tree=Await {param($t) @($t.surfaces).Count -eq 5 -and @($t.surfaces|Where-Object {-not $_.ready -or -not $_.running -or -not $_.pid}).Count -eq 0};Stable $tree $original
 $modeAfter=Request @('read-screen','--surface',$split.surface,'--recent');$diagnostic.inputModesAfter=@{screen=$modeAfter.screen};Require ($modeAfter.screen.buffer -ceq 'normal' -and -not $modeAfter.text.Contains($altMarker)) 'Reconnected SSH retained the previous application alternate screen'
 $cursorAfter=Request @('send-key','Enter','--surface',$split.surface);$diagnostic.inputModesAfter.cursor=$cursorAfter;Require ($cursorAfter.ok -and $cursorAfter.surface -ceq $split.surface -and $cursorAfter.application_cursor -eq $false -and $cursorAfter.accepted_bytes -eq 1 -and $cursorAfter.delivery -ceq 'queued') 'Reconnected SSH retained the previous application cursor mode'
 # A fresh shell may legitimately enable bracketed paste again; do not require it to remain off.
 foreach($s in $sshBefore){$now=@($tree.surfaces|Where-Object {$_.id -ceq $s.id})[0];Require ($now.pid -ne $s.pid -and $now.view_handle -eq $s.view_handle -and $now.holder.window -eq $s.holder.window) 'Reconnect did not replace only the SSH process';Retained-History $s.id $history[$s.id]}
 foreach($identity in @($remote,$tab,$split,$offline)){Remote-Proof $identity.surface $identity.pane $changedDirectory|Out-Null}
 $tree=Await {param($t) $t.ssh_toolbar.state -ceq 'connected'};$bar=Toolbar $tree $remote.workspace 'connected';$connected=@($tree.surfaces);Require (@($connected.pid|Select-Object -Unique).Count -eq 5) 'Reconnect duplicated an SSH process identity';Check-Config $tree $remote.workspace $name|Out-Null
 # Disabled native Connect still receives an owned stale WM_COMMAND; it must be harmless.
 [PaneToolsFixture]::Command($hostProcess,[long]$tree.window_handle,[long]$bar.controls.connect);[PaneToolsFixture]::Command($hostProcess,[long]$tree.window_handle,[long]$bar.controls.connect);$tree=Tree;Stable $tree $connected;Require (@($tree.surfaces).Count -eq 5) 'Repeated Connect added sessions';Passed 'native-Connect-resets-application-modes-keeps-identities-Unicode-history-remote-CWD-and-ignores-repeat'
 $saved=Request @('save-state');$state=[IO.File]::ReadAllText($saved.path,[Text.Encoding]::UTF8)|ConvertFrom-Json;Check-Config $state $remote.workspace $name|Out-Null;Stop-Host
 $tree=Start-Host @('--restore-window',$saved.window) $true;Check-Config $tree $remote.workspace $name|Out-Null;Require (@($tree.surfaces).Count -eq 5 -and @($tree.surfaces|Where-Object {$_.id -in @($remote.surface,$tab.surface,$split.surface,$offline.surface)}).Count -eq 4 -and @($tree.surfaces|Where-Object {$_.id -cne $local.surface -and $_.running}).Count -eq 0 -and @($tree.surfaces|Where-Object {$_.id -ceq $local.surface -and $_.running}).Count -eq 1) 'SSH restore did not preserve identities in the disconnected state'
 $restoredScreen=Request @('read-screen','--surface',$remote.surface,'--recent');$diagnostic.restoredSSHScreen=$restoredScreen;Require ($restoredScreen.text.Contains('[Restored history]') -and -not $restoredScreen.text.Contains('[Restored history — new PowerShell session]')) 'Restored SSH history lacks its shell-neutral marker or labels the session as PowerShell'
 Request @('focus-tab',$remote.surface)|Out-Null;$tree=Tree;$bar=Toolbar $tree $remote.workspace 'disconnected';[OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$bar.controls.connect,$hostProcess.Id);$tree=Await {param($t) @($t.surfaces|Where-Object {-not $_.running -or -not $_.ready}).Count -eq 0};Remote-Proof $remote.surface $remote.pane $changedDirectory|Out-Null;Passed 'save-restore-preserves-NFD-config-paths-stays-disconnected-until-native-Connect-and-executes-remotely'

 # Authentication must expose failed connection output even when a healthy SSH tab is current.
 $tree=Tree;$failedBefore=@($tree.surfaces|Where-Object {$_.id -ceq $remote.surface})[0];$survivors=@($tree.surfaces|Where-Object {$_.id -cne $remote.surface});$authMarker='SSH_AUTH_FAILURE_'+[guid]::NewGuid().ToString('N').Substring(0,8);$authOctal=([Text.Encoding]::UTF8.GetBytes($authMarker)|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join ''
 $authCommand='printf '''+$authOctal+'\n''';if($server){$authCommand='if shopt -q login_shell && [ "$SHLVL" = 1 ]; then '+$authCommand+'; fi'}
 Request @('focus-tab',$remote.surface)|Out-Null;Request @('send-keys',$remote.pane,$authCommand)|Out-Null;Request @('send-key','Enter','--surface',$remote.surface)|Out-Null
 # Confirm output arrived before exit. Remote/client logout may reset its display; Authentication must preserve the finalized post-exit screen.
 $authWait=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$authWait.ElapsedMilliseconds;Require ($left -ge 100) 'SSH failure marker was not displayed within five seconds';$shown=Request @('read-screen','--surface',$remote.surface,'--recent') 0 ([int]$left);$diagnostic.authenticationBeforeExitScreen=$shown;if($shown.text.Replace("`r",'').Replace("`n",'').Contains($authMarker)){break};Start-Sleep -Milliseconds 20}while($true)
 Request @('send-keys',$remote.pane,'exit 17')|Out-Null;Request @('send-key','Enter','--surface',$remote.surface)|Out-Null
 $tree=Await {param($t) @($t.surfaces|Where-Object {$_.id -ceq $remote.surface -and -not $_.running -and $_.exit_code -eq 17 -and $_.resources_released}).Count -eq 1}
 $diagnostic.authenticationAfterExitScreen=Request @('read-screen','--surface',$remote.surface,'--recent')
 $afterExit=$diagnostic.authenticationAfterExitScreen;Require (-not [string]::IsNullOrWhiteSpace($afterExit.text)) 'SSH termination produced no finalized output to preserve'
 Request @('focus-tab',$tab.surface)|Out-Null;$tree=Tree;Require ($tree.ssh_toolbar.state -ceq 'failed' -and [OptionsFixture]::Describe([long]$tree.ssh_toolbar.controls.authentication,$hostProcess.Id).Enabled) 'Failed SSH output has no available Authentication action'
 [OptionsFixture]::ClickMenu([long]$tree.window_handle,[long]$tree.ssh_toolbar.controls.authentication,$hostProcess.Id);$selected=Request @('identify');Require ($selected.surface -ceq $remote.surface -and $selected.workspace -ceq $remote.workspace) 'Authentication selected a healthy tab instead of the failed SSH output'
 $tree=Tree;Stable $tree $survivors;$failedAfter=@($tree.surfaces|Where-Object {$_.id -ceq $remote.surface})[0];Require ($failedAfter.view_handle -eq $failedBefore.view_handle -and $failedAfter.holder.window -eq $failedBefore.holder.window -and -not $failedAfter.running) 'Authentication recreated the failed terminal';$failureScreen=Request @('read-screen','--surface',$remote.surface,'--recent');$diagnostic.failureScreen=$failureScreen;Require ((Same $failureScreen.text $afterExit.text) -and $failureScreen.sequence -eq $afterExit.sequence -and (Same ($failureScreen.screen|ConvertTo-Json -Depth 10 -Compress) ($afterExit.screen|ConvertTo-Json -Depth 10 -Compress))) 'Authentication changed the finalized SSH termination text, sequence or screen metadata';Passed 'Authentication-selects-failed-SSH-output-and-preserves-other-session-PIDs'
 if($server){
  # A non-login shell bypasses Git's system bash.bash_logout without changing any profile.
  Request @('focus-tab',$tab.surface)|Out-Null;Request @('send-keys',$tab.pane,'exec /bin/bash --noprofile --norc -i')|Out-Null;Request @('send-key','Enter','--surface',$tab.surface)|Out-Null
  $nonloginMarker='SSH_NONLOGIN_'+[guid]::NewGuid().ToString('N').Substring(0,8)+' 한글 한 😀';$nonloginOctal=([Text.Encoding]::UTF8.GetBytes($nonloginMarker)|ForEach-Object {'\'+[Convert]::ToString($_,8).PadLeft(3,'0')}) -join ''
  # Only the actual non-login shell may print the full marker; echoed command input cannot match it.
  Request @('send-keys',$tab.pane,('if ! shopt -q login_shell; then printf '''+$nonloginOctal+'\n''; fi'))|Out-Null;Request @('send-key','Enter','--surface',$tab.surface)|Out-Null
  $nonloginWait=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$nonloginWait.ElapsedMilliseconds;Require ($left -ge 100) 'Non-login SSH Unicode marker was not displayed within five seconds';$nonloginBefore=Request @('read-screen','--surface',$tab.surface,'--recent') 0 ([int]$left);$diagnostic.nonloginBeforeExitScreen=$nonloginBefore;if($nonloginBefore.text.Replace("`r",'').Replace("`n",'').Contains($nonloginMarker)){break};Start-Sleep -Milliseconds 20}while($true)
  Request @('send-keys',$tab.pane,'exit 17')|Out-Null;Request @('send-key','Enter','--surface',$tab.surface)|Out-Null
  $tree=Await {param($t) @($t.surfaces|Where-Object {$_.id -ceq $tab.surface -and -not $_.running -and $_.exit_code -eq 17 -and $_.resources_released}).Count -eq 1};$nonloginAfter=Request @('read-screen','--surface',$tab.surface,'--recent');$diagnostic.nonloginAfterExitScreen=$nonloginAfter
  Require ($nonloginAfter.screen.buffer -ceq 'normal' -and $nonloginAfter.text.Replace("`r",'').Replace("`n",'').Contains($nonloginMarker)) 'Non-login SSH exit lost acknowledged Korean/NFD/emoji output';Stable $tree @($survivors|Where-Object {$_.id -cne $tab.surface});Passed 'owned-nonlogin-SSH-exit-preserves-acknowledged-Unicode-output-without-profile-mutations'
 }
 # Leave a real browser tab in the SSH workspace, then close every SSH terminal.
 $browser=(Request @('browser','open','about:blank','--pane',$split.pane)).browser_pane_opened;Require ([bool]$browser.surface) 'SSH browser-only availability case did not create its browser'
 $tree=Await {param($t) @($t.browsers|Where-Object {$_.id -ceq $browser.surface -and -not $_.loading}).Count -eq 1};$browserBefore=@($tree.browsers|Where-Object {$_.id -ceq $browser.surface})[0];$localBefore=@($tree.surfaces|Where-Object {$_.id -ceq $local.surface})
 foreach($surface in @($remote.surface,$tab.surface,$split.surface,$offline.surface)){Request @('close-tab',$surface)|Out-Null};Request @('focus-tab',$browser.surface)|Out-Null
 $tree=Await {param($t) @($t.surfaces).Count -eq 1 -and @($t.browsers|Where-Object {$_.id -ceq $browser.surface}).Count -eq 1};Require ($tree.ssh_toolbar.workspace -ceq $remote.workspace) 'Browser-only case left its SSH workspace';$identity=Request @('identify');$shape=$tree.workspaces|ConvertTo-Json -Depth 40 -Compress;$bar=$tree.ssh_toolbar
 foreach($key in @('authentication','connect','disconnect')){Require (-not [OptionsFixture]::Describe([long]$bar.controls.$key,$hostProcess.Id).Enabled) ('Browser-only SSH workspace exposes unavailable '+$key);[PaneToolsFixture]::Command($hostProcess,[long]$tree.window_handle,[long]$bar.controls.$key)}
 $tree=Tree;$after=Request @('identify');Require ($after.surface -ceq $identity.surface -and (Same ($tree.workspaces|ConvertTo-Json -Depth 40 -Compress) $shape) -and @($tree.surfaces).Count -eq 1) 'Disabled SSH toolbar command changed a browser-only workspace';Stable $tree $localBefore;$browserAfter=@($tree.browsers|Where-Object {$_.id -ceq $browser.surface})[0];Require ($browserAfter.view_handle -eq $browserBefore.view_handle -and $browserAfter.url -ceq 'about:blank') 'Disabled SSH toolbar command replaced its browser';Passed 'browser-only-SSH-workspace-disables-Authentication-Connect-Disconnect-and-ignores-stale-commands'

 Stop-Host
 }
}catch{$failure=$_.Exception.Message}
finally{
 $cleanup=$true
 if($hostProcess){try{if(-not $hostProcess.HasExited -and $pipeName){Request @('quit','--discard-state')|Out-Null;$null=$hostProcess.WaitForExit(3000)}}catch{if(-not $failure){$failure='Cleanup: '+$_.Exception.Message}}
  try{if(-not $hostProcess.HasExited){$hostProcess.Kill();[CliProbe]::WaitAfterKill($hostProcess);if(-not $failure){$failure='Host required forced cleanup'}};$null=$out.Wait(500);$null=$err.Wait(500);$diagnostic.hostStdout=[CliProbe]::Output($out);$diagnostic.hostStderr=[CliProbe]::Output($err)}catch{if(-not $failure){$failure=$_.Exception.Message}}finally{$hostProcess.Dispose()}}
 if($Tmux){$tmuxSessions+=@($diagnostic.lastTree.surfaces|Where-Object {$_.shell.program -ceq 'ssh'}|ForEach-Object {Tmux-Session $_.id});foreach($session in @($tmuxSessions|Select-Object -Unique)){try{Tmux-Remote ('tmux kill-session -t '''+$session+''' 2>/dev/null || true')|Out-Null;Tmux-Remote ('tmux has-session -t '''+$session+'''') 1|Out-Null}catch{if(-not $failure){$failure='Owned tmux session cleanup: '+$_.Exception.Message}}}}
 if($server){try{if(-not $server.HasExited){$server.Kill();[CliProbe]::WaitAfterKill($server)};Require ($serverOut.Wait(500)-and $serverErr.Wait(500)) 'sshd output pipes did not close';$diagnostic.serverStderr=[CliProbe]::Output($serverErr)}catch{if(-not $failure){$failure='sshd cleanup: '+$_.Exception.Message}}finally{$server.Dispose()}}
 if($httpFixture){try{$httpFixture.Dispose()}catch{if(-not $failure){$failure='HTTP fixture cleanup: '+$_.Exception.Message}}}
 try{$fixture.Dispose()}catch{if(-not $failure){$failure='Fixture cleanup: '+$_.Exception.Message}}
}
if($failure){$diagnostic.failure=$failure;$diagnostic.elapsedMs=$clock.ElapsedMilliseconds;$diagnostic|ConvertTo-Json -Depth 60|Set-Content -Encoding UTF8 -LiteralPath (Join-Path $directory 'failure.json');throw $failure}
Remove-Item -LiteralPath $directory -Recurse -Force
Write-Output ("passed: $checks hidden SSH groups (tmux=$Tmux; ports=$Ports); actual loopback/external SSH Unicode and remote-CWD markers verified; elapsed="+$clock.ElapsedMilliseconds+'ms')
