# SPDX-License-Identifier: GPL-3.0-or-later
# Real Git/tig, owned hidden host only. Run through run-check.ps1 with an80s cap.
param([string]$BuildDirectory="$PSScriptRoot\..\target\x86_64-pc-windows-msvc\debug")
if(-not $env:FLOWMUX_TEST_ARTIFACT_ROOT){throw 'Run this verifier through windows/scripts/run-check.ps1 so temporary artifacts are cleaned automatically.'}
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=New-Object Text.UTF8Encoding($false)
$BuildDirectory=(Resolve-Path $BuildDirectory).Path;$gui=Join-Path $BuildDirectory 'flowmux.exe';$cli=Join-Path $BuildDirectory 'flowmuxctl.exe';$gitCmd=Join-Path $env:ProgramFiles 'Git\cmd';$gitUsr=Join-Path $env:ProgramFiles 'Git\usr\bin';$git=Join-Path $gitCmd 'git.exe';$tig=Join-Path $gitUsr 'tig.exe'
Add-Type -Path (Join-Path $PSScriptRoot 'CliProbe.cs'),(Join-Path $PSScriptRoot 'OptionsFixture.cs')
$directory=Join-Path $env:FLOWMUX_TEST_ARTIFACT_ROOT ('open-tig-'+[guid]::NewGuid());$repo=Join-Path $directory '한글 저장소 한 😀';[IO.Directory]::CreateDirectory($repo)|Out-Null
$clock=[Diagnostics.Stopwatch]::StartNew();$owned=$null;$pipeName=$null;$hostOut=$null;$hostErr=$null;$failure=$null;$cleanupErrors=@();$cleaning=$false;$checks=@();$savedEnvironment=@{};$diagnostic=[ordered]@{physicalInput=$false;clipboardAccess=$false;checks=@();lastTree=$null}
function Require([bool]$Value,[string]$Message){if(-not $Value){throw $Message}}
function Same([string]$A,[string]$B){return [string]::Equals($A,$B,[StringComparison]::Ordinal)}
function Path-Same([string]$A,[string]$B){return [string]::Equals($A.Replace('/','\').TrimEnd('\'),$B.Replace('/','\').TrimEnd('\'),[StringComparison]::OrdinalIgnoreCase)}
function Budget([int]$Maximum=5000){if($cleaning){return [Math]::Min($Maximum,2000)};$left=75000-$clock.ElapsedMilliseconds;Require ($left -gt 0) 'Open tig verification exceeded75s';return [int][Math]::Min($Maximum,$left)}
function Run([string]$File,[string[]]$Arguments,[int]$Maximum=5000){
 $diagnostic.lastCommand=@{file=$File;arguments=$Arguments};$p=[CliProbe]::Start($File,$Arguments,$repo,$directory);$out=$p.StandardOutput.ReadToEndAsync();$err=$p.StandardError.ReadToEndAsync()
 try{Require ($p.WaitForExit((Budget $Maximum))) 'Owned command exceeded bounded deadline';Require ($out.Wait(500)-and $err.Wait(500)) 'Owned command pipes did not close';Require ($p.ExitCode -eq 0) ('Owned command failed: '+[CliProbe]::Output($err));return [CliProbe]::Output($out)}
 catch{$diagnostic.commandFailure=@{arguments=$Arguments;stdout=[CliProbe]::Output($out);stderr=[CliProbe]::Output($err)};throw}
 finally{if(-not $p.HasExited){$p.Kill();[CliProbe]::WaitAfterKill($p)};$p.Dispose()}
}
function Git([string[]]$Arguments){return Run $git (@('-c','core.quotePath=false','-c','commit.gpgSign=false','-c','core.autocrlf=false','-C',$repo)+$Arguments)}
function Request([string[]]$Arguments,[int]$Maximum=5000){Require ([bool]$pipeName) 'Explicit owned pipe required';return ((Run $cli (@('--pipe',$pipeName,'--json')+$Arguments) $Maximum)|ConvertFrom-Json)}
function Tree([int]$Maximum=5000){$t=Request @('tree') $Maximum;Require ($t.background_testing -and -not $owned.HasExited) 'Owned hidden host unavailable';[OptionsFixture]::Describe([long]$t.window_handle,$owned.Id)|Out-Null;$diagnostic.lastTree=$t;return $t}
function Await([scriptblock]$Condition){$watch=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$watch.ElapsedMilliseconds;Require ($left -ge 100) 'Open tig condition exceeded5s';$t=Tree ([int]$left);if(& $Condition $t){return $t};Start-Sleep -Milliseconds 20}while($true)}
function Screen([string]$Surface,[scriptblock]$Condition){$watch=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$watch.ElapsedMilliseconds;Require ($left -ge 100) 'Actual tig/shell screen exceeded5s';$s=Request @('read-screen','--surface',$Surface,'--recent') ([int]$left);$diagnostic.lastScreen=$s;if(& $Condition $s){return $s};Start-Sleep -Milliseconds 20}while($true)}
function Stable($Before){$t=Tree;foreach($s in $Before){$n=@($t.surfaces|Where-Object {$_.id -ceq $s.id});Require ($n.Count -eq 1 -and $n[0].pid -eq $s.pid -and $n[0].session -ceq $s.session -and $n[0].view_handle -eq $s.view_handle -and $n[0].holder.window -eq $s.holder.window -and $n[0].running) 'Open tig changed an existing terminal PID/session/view'};return $t}
function Shortcut([string]$Surface,[hashtable]$Event,[bool]$Forwarded){$r=Request @('test-shortcut',$Surface,($Event|ConvertTo-Json -Compress));Require ($r.surface -ceq $Surface -and $r.forwarded -eq $Forwarded) 'Actual renderer shortcut returned the wrong decision'}
function Tig-Started($Before,[string]$ExpectShell='cmd'){
 $ids=@($Before|ForEach-Object {$_.id});$tree=Await {param($t) @($t.surfaces).Count -eq $ids.Count+1 -and @($t.surfaces|Where-Object {$_.id -cnotin $ids -and $_.ready -and $_.running}).Count -eq 1};$new=@($tree.surfaces|Where-Object {$_.id -cnotin $ids})[0];$identity=Request @('identify')
 Require ($identity.surface -ceq $new.id -and $identity.pane -ceq $source.pane -and $identity.workspace -ceq $source.workspace -and (Path-Same $identity.cwd $repo)) 'Open tig did not select one new tab in the same pane/workspace and exact Unicode/NFD cwd';Require ([IO.Path]::GetFileNameWithoutExtension($new.shell.program) -ieq $ExpectShell) 'Open tig replaced the configured default shell'
 # Check Hangul/NFD in tig; check the complete subject including emoji through Git after q.
 Screen $new.id {param($s) $s.screen.buffer -ceq 'alternate' -and $s.text.Contains($tigSubject)}|Out-Null;Stable $Before|Out-Null;return $new
}
function Quit-Tig($Surface,[string]$ExpectShell='cmd'){
 Request @('send-keys',$source.pane,'q')|Out-Null;Screen $Surface.id {param($s) $s.screen.buffer -ceq 'normal'}|Out-Null
 Request @('send-keys',$source.pane,'git --no-pager log -1 --format=%s')|Out-Null;Request @('send-key','Enter','--surface',$Surface.id)|Out-Null;Screen $Surface.id {param($s) $s.screen.buffer -ceq 'normal' -and $s.text.Contains($subject)}|Out-Null
 $marker='TIG_RETURN_'+$Surface.id;$command=if($ExpectShell -ieq 'powershell'){'Write-Output (''TIG_RETURN_'' + $env:FLOWMUX_SURFACE_ID)'}else{'echo TIG_RETURN_%FLOWMUX_SURFACE_ID%'};Request @('send-keys',$source.pane,$command)|Out-Null;Request @('send-key','Enter','--surface',$Surface.id)|Out-Null;Screen $Surface.id {param($s) $s.screen.buffer -ceq 'normal' -and $s.text.Replace("`r",'').Replace("`n",'').Contains($marker)}|Out-Null
 Stable @($Surface)|Out-Null
}
function Passed([string]$Name){$script:checks+=,$Name;$diagnostic.checks=$checks}
try{
 Require ((Test-Path -LiteralPath $git)-and (Test-Path -LiteralPath $tig)) 'Actual Git for Windows git.exe and usr/bin/tig.exe are required'
 foreach($name in @('PATH','LOCALAPPDATA','LANG','LC_ALL','TIGRC_USER','TIGRC_SYSTEM','GIT_CONFIG_NOSYSTEM','GIT_CONFIG_GLOBAL','GIT_CONFIG_SYSTEM','GIT_DIR','GIT_WORK_TREE','GIT_COMMON_DIR','GIT_INDEX_FILE','GIT_OBJECT_DIRECTORY','GIT_ALTERNATE_OBJECT_DIRECTORIES','GIT_CONFIG','GIT_CONFIG_PARAMETERS','GIT_CONFIG_COUNT')){$savedEnvironment[$name]=[Environment]::GetEnvironmentVariable($name,'Process');[Environment]::SetEnvironmentVariable($name,$null,'Process')}
 $empty=Join-Path $directory 'empty-config';[IO.File]::WriteAllText($empty,'');$hooks=Join-Path $directory 'no-hooks';[IO.Directory]::CreateDirectory($hooks)|Out-Null;$local=Join-Path $directory 'localappdata';[IO.Directory]::CreateDirectory($local)|Out-Null
 [Environment]::SetEnvironmentVariable('PATH',($BuildDirectory+';'+$gitUsr+';'+$gitCmd+';'+(Join-Path $env:WINDIR 'System32')+';'+$env:WINDIR+';'+(Join-Path $env:WINDIR 'System32\WindowsPowerShell\v1.0')),'Process');[Environment]::SetEnvironmentVariable('LOCALAPPDATA',$local,'Process')
 foreach($name in @('LANG','LC_ALL')){[Environment]::SetEnvironmentVariable($name,'C.UTF-8','Process')};foreach($name in @('TIGRC_USER','GIT_CONFIG_GLOBAL','GIT_CONFIG_SYSTEM')){[Environment]::SetEnvironmentVariable($name,$empty,'Process')};[Environment]::SetEnvironmentVariable('GIT_CONFIG_NOSYSTEM','1','Process')
 $systemTig=Join-Path $env:ProgramFiles 'Git\etc\tigrc';Require (Test-Path -LiteralPath $systemTig) 'Installed default tig configuration is missing';[Environment]::SetEnvironmentVariable('TIGRC_SYSTEM',$systemTig,'Process')
 Git @('init','--initial-branch=main')|Out-Null;Git @('config','user.name','Owned tig fixture')|Out-Null;Git @('config','user.email','tig@example.invalid')|Out-Null;Git @('config','core.hooksPath',$hooks)|Out-Null
 $tigSubject='TIG_'+[guid]::NewGuid().ToString('N').Substring(0,8)+' 한글 한';$subject=$tigSubject+' 😀';[IO.File]::WriteAllText((Join-Path $repo '변경 한.txt'),"한글 fixture`n",(New-Object Text.UTF8Encoding($false)));Git @('add','--all')|Out-Null;Git @('commit','-m',$subject)|Out-Null;Require (Same (Git @('log','-1','--format=%s')).Trim() $subject) 'Actual Git commit subject differs'
 $started=[DateTime]::UtcNow;$watch=[Diagnostics.Stopwatch]::StartNew();$owned=[CliProbe]::Start($gui,@('--temporary','--shell=cmd','--cwd',$repo),$repo,$directory);$hostOut=$owned.StandardOutput.ReadToEndAsync();$hostErr=$owned.StandardError.ReadToEndAsync();$discovery=Join-Path $env:LOCALAPPDATA ('flowmux\windows\instances\'+$owned.Id+'.json')
 do{Budget|Out-Null;Require (-not $owned.HasExited -and $watch.ElapsedMilliseconds -lt 8000) 'Owned hidden startup exceeded8s';if((Test-Path -LiteralPath $discovery)-and (Get-Item -LiteralPath $discovery).LastWriteTimeUtc -ge $started){$record=Get-Content -Raw -LiteralPath $discovery|ConvertFrom-Json;Require ($record.pid -eq $owned.Id) 'Wrong discovery host';$pipeName=$record.pipe;break};Start-Sleep -Milliseconds 20}while($true)
 $tree=Await {param($t) @($t.surfaces).Count -eq 1 -and $t.surfaces[0].ready -and $t.surfaces[0].running};$source=Request @('identify');Require (Path-Same $source.cwd $repo) 'Initial terminal cwd differs';Request @('settings','shell','cmd','--arg','/d')|Out-Null
 $tree=Await {param($t) @($t.surfaces[0].settings.bindings|Where-Object {$_.action -ceq 'open-tig' -and $_.chord.code -ceq 'KeyG' -and $_.chord.ctrl -and $_.chord.alt -and -not $_.chord.shift}).Count -eq 1};$before=@($tree.surfaces);$default=@{code='KeyG';key='g';ctrlKey=$true;altKey=$true}
 foreach($guard in @(@{repeat=$true;forwarded=$false},@{isComposing=$true;forwarded=$true},@{keyCode=229;forwarded=$true})){$event=$default.Clone();$forwarded=$guard.forwarded;foreach($name in $guard.Keys){if($name -ne 'forwarded'){$event[$name]=$guard[$name]}};Shortcut $source.surface $event $forwarded;$tree=Stable $before;Require (@($tree.surfaces).Count -eq 1) 'Guarded Open tig created a tab'}
 Shortcut $source.surface $default $false;$first=Tig-Started $before;Passed 'default-CtrlAltG-real-tig-Hangul-NFD-commit-same-pane-cwd-and-repeat-IME-229-guards'
 Quit-Tig $first;Passed 'q-returns-to-same-shell-and-Git-preserves-full-Hangul-NFD-emoji-subject'
 Request @('settings','keybindings','set','open-tig','Ctrl+Alt+Y')|Out-Null;$tree=Await {param($t) @($t.surfaces|Where-Object {@($_.settings.bindings|Where-Object {$_.action -ceq 'open-tig' -and $_.chord.code -ceq 'KeyY' -and $_.chord.ctrl -and $_.chord.alt}).Count -eq 1}).Count -eq @($t.surfaces).Count};$before=@($tree.surfaces)
 Shortcut $first.id $default $true;Require (@((Stable $before).surfaces).Count -eq $before.Count) 'Old tig binding remained active';Shortcut $first.id @{code='KeyY';key='y';ctrlKey=$true;altKey=$true} $false;$second=Tig-Started $before;Quit-Tig $second;Passed 'custom-binding-replaces-default-and-opens-second-actual-tig-tab'
 $tree=Tree;$before=@($tree.surfaces);$button=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'command_palette' -and $_.layout_visible});Require ($button.Count -eq 1) 'Command Palette toolbar entry missing';[OptionsFixture]::Click([OptionsFixture]::Parent([long]$button[0].handle,$owned.Id),[long]$button[0].handle,$owned.Id)
 $tree=Await {param($t) $t.command_palette.open};$palette=$tree.command_palette;[OptionsFixture]::SetTextAndNotify([long]$palette.window,[long]$palette.query_handle,$owned.Id,'Open tig');$tree=Await {param($t) $t.command_palette.open -and $t.command_palette.query -ceq 'Open tig' -and @($t.command_palette.filtered) -ccontains 'action:open-tig'};$palette=$tree.command_palette;$index=[Array]::IndexOf(@($palette.filtered),'action:open-tig');$current=[int]$palette.selected_index;$key=if($current -gt $index){38}else{40}
 for($i=0;$i -lt [Math]::Abs($index-$current);$i++){[OptionsFixture]::PostKey([long]$palette.query_handle,$owned.Id,$key,$false,$false);[OptionsFixture]::PostKey([long]$palette.query_handle,$owned.Id,$key,$true,$false)};$tree=Await {param($t) $t.command_palette.selected -ceq 'action:open-tig'};[OptionsFixture]::PostEnter([long]$tree.command_palette.query_handle,$owned.Id);$third=Tig-Started $before;Require ([OptionsFixture]::Describe([long](Tree).window_handle,$owned.Id).Enabled) 'Palette launch left its owner disabled';Quit-Tig $third;Passed 'Command-Palette-Open-tig-dispatches-real-program-and-restores-owner'
 Request @('settings','shell','powershell')|Out-Null;$revision=(Request @('settings','show')).document.revision;Require ([bool]$revision) 'PowerShell setting has no revision'
 $tree=Await {param($t) @($t.surfaces|Where-Object {$_.settings.revision -cne $revision}).Count -eq 0};$before=@($tree.surfaces);Shortcut $third.id @{code='KeyY';key='y';ctrlKey=$true;altKey=$true} $false;$fourth=Tig-Started $before 'powershell';Quit-Tig $fourth 'powershell';Passed 'PowerShell-startup-retains-tig-launch-and-q-returns-to-same-live-shell-with-env-proof'
}
catch{$failure=$_.Exception.Message}
finally{
 $cleaning=$true
 if($owned){try{if(-not $owned.HasExited){Request @('quit','--discard-state')|Out-Null;Require ($owned.WaitForExit(4000)) 'Owned host quit timed out'};Require ($owned.ExitCode -eq 0) 'Owned host failed'}catch{$cleanupErrors+=,$_.Exception.Message}finally{try{if(-not $owned.HasExited){$owned.Kill();[CliProbe]::WaitAfterKill($owned)};$diagnostic.host=@{pid=$owned.Id;exitCode=$owned.ExitCode;stdout=[CliProbe]::Output($hostOut);stderr=[CliProbe]::Output($hostErr)}}catch{$cleanupErrors+=,$_.Exception.Message}finally{$owned.Dispose()}}}
 foreach($name in $savedEnvironment.Keys){[Environment]::SetEnvironmentVariable($name,$savedEnvironment[$name],'Process')}
}
if($failure -or $cleanupErrors.Count){$diagnostic.failure=$failure;$diagnostic.cleanupErrors=$cleanupErrors;$diagnostic.elapsedMs=$clock.ElapsedMilliseconds;$diagnostic|ConvertTo-Json -Depth 50|Set-Content -Encoding UTF8 -LiteralPath (Join-Path $directory 'failure.json');throw ($failure+' '+($cleanupErrors -join '; '))}
Remove-Item -LiteralPath $directory -Recurse -Force
Write-Output ('passed: '+$checks.Count+' real-tig hidden groups; elapsed='+$clock.ElapsedMilliseconds+'ms')
