# SPDX-License-Identifier: GPL-3.0-or-later
# Owned hidden UI with real domain parsers; no account/network collection.
param([string]$BuildDirectory="$PSScriptRoot\..\target\x86_64-pc-windows-msvc\debug")
if(-not $env:FLOWMUX_TEST_ARTIFACT_ROOT){throw 'Run this verifier through windows/scripts/run-check.ps1 so temporary artifacts are cleaned automatically.'}
$ErrorActionPreference='Stop';$OutputEncoding=[Console]::OutputEncoding=New-Object Text.UTF8Encoding($false)
$BuildDirectory=(Resolve-Path $BuildDirectory).Path;$gui=Join-Path $BuildDirectory 'flowmux.exe';$cli=Join-Path $BuildDirectory 'flowmuxctl.exe'
Add-Type -Path (Join-Path $PSScriptRoot 'CliProbe.cs'),(Join-Path $PSScriptRoot 'OptionsFixture.cs'),(Join-Path $PSScriptRoot 'PaneToolsFixture.cs'),(Join-Path $PSScriptRoot 'FindFixture.cs')
Add-Type -ReferencedAssemblies System.Drawing -Path (Join-Path $PSScriptRoot 'ChromeFixture.cs')
$directory=Join-Path $env:FLOWMUX_TEST_ARTIFACT_ROOT ('usage-'+[guid]::NewGuid());[IO.Directory]::CreateDirectory($directory)|Out-Null
$clock=[Diagnostics.Stopwatch]::StartNew();$owned=$null;$pipeName=$null;$hostOut=$null;$hostErr=$null;$failure=$null;$cleanupErrors=@();$cleaning=$false;$checks=@();$savedLocal=$env:LOCALAPPDATA
$diagnostic=[ordered]@{physicalInput=$false;clipboardAccess=$false;accountCollection=$false;checks=@();lastTree=$null}
function Require([bool]$Value,[string]$Message){if(-not $Value){throw $Message}}
function Budget([int]$Maximum=5000){if($cleaning){return [Math]::Min($Maximum,2000)};$left=75000-$clock.ElapsedMilliseconds;Require ($left -gt 0) 'Usage verification exceeded75s';return [int][Math]::Min($Maximum,$left)}
function Request([string[]]$Arguments,[int]$Maximum=5000){
 Require ([bool]$pipeName) 'Explicit owned pipe required';$diagnostic.lastCommand=$Arguments;$p=[CliProbe]::Start($cli,(@('--pipe',$pipeName,'--json')+$Arguments),$directory,$directory);$out=$p.StandardOutput.ReadToEndAsync();$err=$p.StandardError.ReadToEndAsync()
 try{Require ($p.WaitForExit((Budget $Maximum))) 'Owned CLI exceeded deadline';Require ($out.Wait(500)-and $err.Wait(500)) 'Owned CLI pipes did not close';Require ($p.ExitCode -eq 0) ('Owned CLI failed: '+[CliProbe]::Output($err));return ([CliProbe]::Output($out)|ConvertFrom-Json)}
 catch{$diagnostic.commandFailure=@{arguments=$Arguments;stdout=[CliProbe]::Output($out);stderr=[CliProbe]::Output($err)};throw}
 finally{if(-not $p.HasExited){$p.Kill();[CliProbe]::WaitAfterKill($p)};$p.Dispose()}
}
function Tree([int]$Maximum=5000){$t=Request @('tree') $Maximum;Require ($t.background_testing -and -not $owned.HasExited) 'Owned hidden host unavailable';Require (-not [CliProbe]::IsWindowVisible([IntPtr][long]$t.window_handle)) 'Owned main unexpectedly visible';[OptionsFixture]::Describe([long]$t.window_handle,$owned.Id)|Out-Null;$diagnostic.lastTree=$t;return $t}
function Await([scriptblock]$Condition){$watch=[Diagnostics.Stopwatch]::StartNew();do{$left=5000-$watch.ElapsedMilliseconds;Require ($left -ge 100) 'Usage condition exceeded5s';$t=Tree ([int]$left);if(& $Condition $t){return $t};Start-Sleep -Milliseconds 20}while($true)}
function Click([long]$Handle){[OptionsFixture]::Click([OptionsFixture]::Parent($Handle,$owned.Id),$Handle,$owned.Id)}
function Stable($Tree){$s=@($Tree.surfaces|Where-Object {$_.id -ceq $original.id});Require ($s.Count -eq 1 -and @($Tree.surfaces).Count -eq 1 -and $s[0].pid -eq $original.pid -and $s[0].session -ceq $original.session -and $s[0].view_handle -eq $original.view_handle -and $s[0].holder.window -eq $original.holder.window -and $s[0].running) 'Usage changed the live terminal PID/session/view/holder';Require ([OptionsFixture]::Describe([long]$Tree.window_handle,$owned.Id).Enabled) 'Usage disabled its owner'}
function Passed([string]$Name){$script:checks+=,$Name;$diagnostic.checks=$checks;Stable (Tree)}
function Panel($Tree){$p=$Tree.usage.panel;Require ($p.open -and $p.window -and -not $p.native_visible) 'Usage popover not logically open and physically hidden';$native=[OptionsFixture]::Describe([long]$p.window,$owned.Id);Require ($native.Owner -eq $Tree.window_handle -and $native.OwnerEnabled -and [Math]::Abs($native.Width-360*$native.Dpi/96) -le 3) 'Usage popup owner/360DIP width differs';Require (@($p.cards).Count -eq 2) 'Expected Claude and Codex native cards';foreach($card in $p.cards){Require ([OptionsFixture]::Text([long]$card.window,$owned.Id) -ceq $card.text) 'Native card caption differs from retained original text'};Header $Tree $p;return $p}
function Header($Tree,$Panel){
 $controls=@([ChromeFixture]::Read([long]$Panel.window,$owned.Id));$header=@();$client=[ChromeFixture]::Size([long]$Panel.window,$owned.Id)
 foreach($key in @('title','toggle','refresh','spinner')){$control=@($controls|Where-Object {$_.Handle -eq [long]$Panel.$key});Require ($control.Count -eq 1) ('Usage header native control missing: '+$key);$header+=,$control[0]}
 Require ($header[0].Text -ceq 'AI Usage' -and $header[1].Text -ceq 'Show bar' -and $header[2].Text -ceq 'Refresh usage' -and $header[3].Text -ceq 'Refreshing usage') 'Usage header lost its native accessible labels'
 Require (($header[1].Style -band 15) -eq 3 -and ($header[1].Style -band 0x1000) -ne 0 -and [OptionsFixture]::Checked([long]$Panel.window,[long]$Panel.toggle,$owned.Id) -eq [bool]$Tree.usage.bar.enabled) 'Show bar lost its native push-checkbox type or checked state'
 $scale=[OptionsFixture]::Describe([long]$Panel.window,$owned.Id).Dpi/96.0;foreach($button in @($header[1],$header[2])){Require ([Math]::Abs($button.Width-28*$scale) -le 2 -and [Math]::Abs($button.Height-28*$scale) -le 2) 'Usage header actions are not compact28DIP icon controls'}
 Require ($header[0].Shown -and $header[1].Shown -and $header[2].Shown -and $header[3].Shown -eq [bool]$Tree.usage.state.refreshing -and $header[2].Enabled -eq (-not $Tree.usage.state.refreshing)) 'Usage spinner visibility or Refresh enabled state differs from the active request'
 foreach($control in $header){Require ($control.X -ge 0 -and $control.Y -ge 0 -and $control.Width -gt 0 -and $control.Height -gt 0 -and $control.X+$control.Width -le $client[0] -and $control.Y+$control.Height -le $client[1] -and $control.Font -ne 0) 'Usage header control escaped the native popup or lost its font'}
 $shown=@($header|Where-Object {$_.Shown});for($i=0;$i -lt $shown.Count-1;$i++){Require ($shown[$i].X+$shown[$i].Width -le $shown[$i+1].X) 'Usage title/toggle/refresh/spinner order overlaps'}
}
function Color([long]$Value){return ('#{0:x2}{1:x2}{2:x2}' -f ($Value-band 255),(($Value-shr 8)-band 255),(($Value-shr 16)-band 255))}
function Paint($Tree,[bool]$Meters=$true){
 $p=Panel $Tree;$path=Join-Path $directory 'usage.bmp';$capture=Request @('chrome-capture',$path);Require ($capture.root_handle -eq $p.window) 'Capture did not target the actual usage popup';$diagnostic.lastCapture=$capture
 foreach($key in @('toggle','refresh','spinner')){
  $glyph=@($capture.controls|Where-Object {$_.handle -eq [long]$p.$key})
  if($key -eq 'spinner' -and -not $Tree.usage.state.refreshing){Require ($glyph.Count -eq 0) 'Idle spinner still appeared in production capture';continue}
  Require ($glyph.Count -eq 1) ('Production capture omitted Usage header glyph: '+$key);$clip=$glyph[0].clip;$pixels=0
  foreach($color in @(@($p.colors.foreground,$p.colors.muted,$p.colors.progress)|Select-Object -Unique)){$pixels+=[ChromeFixture]::ColorCount($path,[int]$clip.x,[int]$clip.y,[int]$clip.width,[int]$clip.height,(Color $color))}
  Require ($pixels -gt 5) ('Production Usage header glyph was blank: '+$key)
 }
 if($Meters){
 $painted=@($capture.controls|Where-Object {$_.handle -eq $p.cards[0].window});Require ($painted.Count -eq 1) 'Production capture omitted Claude ownerdraw';$rect=$painted[0].clip;Require ($rect.width -gt 0 -and $rect.height -gt 0) 'Claude production paint is clipped away'
 Require ([ChromeFixture]::ColorCount($path,[int]$rect.x,[int]$rect.y,[int]$rect.width,[int]$rect.height,(Color $p.colors.progress)) -gt 10) 'Production ownerdraw did not paint the positive usage meter'
 Require ([ChromeFixture]::ColorCount($path,[int]$rect.x,[int]$rect.y,[int]$rect.width,[int]$rect.height,(Color $p.colors.foreground)) -gt 10) 'Production ownerdraw did not paint provider content'
 };Remove-Item -LiteralPath $path -Force
}
function Bar-Paint($Tree,[bool]$Narrow=$false){
 $bar=$Tree.usage.bar;$scale=[OptionsFixture]::Describe([long]$bar.window,$owned.Id).Dpi/96.0;$size=[ChromeFixture]::Size([long]$bar.window,$owned.Id);$meters=@($bar.meters)
 Require ($bar.enabled -and -not $bar.native_visible -and [OptionsFixture]::Parent([long]$bar.window,$owned.Id) -eq $Tree.window_handle -and [OptionsFixture]::Parent([long]$bar.control,$owned.Id) -eq $bar.window -and [Math]::Abs($size[1]-20*$scale) -le 1) 'Usage bar lost its owned hidden20DIP row'
 Require ($meters.Count -eq 4 -and (@($meters.provider)-join ',') -ceq 'claude,claude,codex,codex' -and (@($meters.label)-join ',') -ceq '5h,1W,5h,1W') 'Usage inline provider/period order differs'
 Require ([OptionsFixture]::Text([long]$bar.control,$owned.Id) -ceq (@($meters.text)-join '; ') -and $bar.tooltip -ceq (@($meters.text)-join '; ')) 'Usage native accessible caption lost period/provider or stale state'
 $native=@([ChromeFixture]::Read([long]$bar.window,$owned.Id)|Where-Object {$_.Handle -eq $bar.control});Require ($native.Count -eq 1 -and $native[0].Font -ne 0 -and $native[0].X -eq 0 -and $native[0].Y -eq 0 -and $native[0].Width -eq $size[0] -and $native[0].Height -eq $size[1]) 'Usage native painter escaped its row'
 $path=Join-Path $directory 'usage-bar.bmp';$capture=Request @('chrome-capture',$path,'--usage-bar');$diagnostic.lastCapture=$capture
 Require ($capture.root_handle -eq $bar.window -and @($capture.controls|Where-Object {$_.handle -eq $bar.control}).Count -eq 1) 'Usage bar capture did not invoke its actual child painter'
 $bitmap=New-Object Drawing.Bitmap($path)
 try{
  $previousRight=0;$trackY=$null;$icons=0
  Require ([ChromeFixture]::ColorCount($path,0,0,$size[0],[int][Math]::Round($scale),(Color $Tree.usage.panel.colors.track)) -eq $size[0]*[int][Math]::Round($scale)) 'Usage row lost its one-DIP top border'
  for($index=0;$index -lt $meters.Count;$index++){
   $meter=$meters[$index];$layout=$bar.geometry.meters[$index];$track=$layout.track;$label=$layout.text;$icon=$null;if($index -eq 0 -or $meters[$index-1].provider -cne $meter.provider){$icon=@($bar.geometry.icons|Where-Object {$_.provider -ceq $meter.provider})[0].rect};$rects=@($track,$label);if($icon){$rects=@($icon)+$rects;$icons++}
   foreach($rect in $rects){Require ($rect.x -ge $previousRight -and $rect.y -ge 0 -and $rect.width -ge 0 -and $rect.height -gt 0 -and $rect.x+$rect.width -le $size[0] -and $rect.y+$rect.height -le $size[1]) 'Usage inline icon/track/label overlaps or escapes row';$previousRight=$rect.x+$rect.width}
   Require ([Math]::Abs($track.height-4*$scale) -le 1 -and $track.width -ge 0 -and $track.width -le [Math]::Round(95*$scale)+1) 'Usage trough height/width differs';if(-not $Narrow){Require ([Math]::Abs($track.width-95*$scale) -le 1) 'Full-width usage trough is not95DIP'}else{Require ($track.width -lt 95*$scale) 'Narrow usage row did not shrink its troughs'}
   if($null -ne $trackY){Require ($track.y -eq $trackY) 'Usage periods are not on one line'};$trackY=$track.y
   Require ($label.x -ge $track.x+$track.width+[Math]::Round(4*$scale)-1 -and $track.y -ge $label.y -and $track.y+$track.height -le $label.y+$label.height -and $meter.display_text -ceq ([string][Math]::Round($meter.percent)+'%('+$meter.label+')')) 'Usage percent label is not inline with its trough'
   $fill=if($meter.provider -ceq 'claude'){'#d97757'}else{'#7a9dff'};$filled=[int][Math]::Round($track.width*[Math]::Min(100,[Math]::Max(0,$meter.percent))/100,[MidpointRounding]::AwayFromZero)
   if($track.width -gt 0){Require ([ChromeFixture]::ColorCount($path,[int]$track.x,[int]$track.y,[int]$track.width,[int]$track.height,$fill) -eq $filled*$track.height) 'Usage provider color or actual percent fill differs'
   Require ([ChromeFixture]::ColorCount($path,[int]$track.x,[int]$track.y,[int]$track.width,[int]$track.height,(Color $Tree.usage.panel.colors.track)) -eq ($track.width-$filled)*$track.height) 'Usage unfilled track pixels differ'}
   if($icon){Require ([Math]::Abs($icon.width-14*$scale) -le 1 -and [Math]::Abs($icon.height-14*$scale) -le 1) 'Usage provider icon size differs';$background=$bitmap.GetPixel([int]$icon.x,[int]($size[1]-1)).ToArgb();$pixels=0;for($y=[int]$icon.y;$y -lt $icon.y+$icon.height;$y++){for($x=[int]$icon.x;$x -lt $icon.x+$icon.width;$x++){if($bitmap.GetPixel($x,$y).ToArgb() -ne $background){$pixels++}}};Require ($pixels -gt 5) 'Usage provider icon was not painted'}
  }
  Require ($icons -eq 2) 'Usage row must paint one icon per provider'
 }finally{$bitmap.Dispose()}
 Remove-Item -LiteralPath $path -Force
}
function Inject($Value){Request @('test-usage',($Value|ConvertTo-Json -Depth 30 -Compress))|Out-Null;return Await {param($t) -not $t.usage.state.refreshing -and -not $t.usage.worker_active}}
function Shortcut(){Request @('test-shortcut',$source.surface,'{"code":"KeyU","key":"u","ctrlKey":true,"altKey":true}')|Out-Null}
function Close-Popup($Tree){[OptionsFixture]::PostEscape([long]$Tree.usage.panel.toggle,$owned.Id);return Await {param($t) -not $t.usage.panel.open}}
function Pane-Height($Tree){$entry=@($Tree.layout.panes|Where-Object {$_[0] -ceq $source.pane});Require ($entry.Count -eq 1) 'Original pane geometry missing';return [int]$entry[0][1].height}
try{
 $env:LOCALAPPDATA=Join-Path $directory 'localappdata';[IO.Directory]::CreateDirectory($env:LOCALAPPDATA)|Out-Null
 $started=[DateTime]::UtcNow;$watch=[Diagnostics.Stopwatch]::StartNew();$owned=[CliProbe]::Start($gui,@('--temporary','--shell=cmd','--cwd',$directory),$directory,$directory);$hostOut=$owned.StandardOutput.ReadToEndAsync();$hostErr=$owned.StandardError.ReadToEndAsync();$discovery=Join-Path $env:LOCALAPPDATA ('flowmux\windows\instances\'+$owned.Id+'.json')
 do{Budget|Out-Null;Require (-not $owned.HasExited -and $watch.ElapsedMilliseconds -lt 8000) 'Owned hidden startup exceeded8s';if((Test-Path -LiteralPath $discovery)-and (Get-Item -LiteralPath $discovery).LastWriteTimeUtc -ge $started){$record=Get-Content -Raw -LiteralPath $discovery|ConvertFrom-Json;Require ($record.pid -eq $owned.Id) 'Wrong discovery host';$pipeName=$record.pipe;break};Start-Sleep -Milliseconds 20}while($true)
 $tree=Await {param($t) @($t.surfaces).Count -eq 1 -and $t.surfaces[0].ready -and $t.surfaces[0].running};$original=$tree.surfaces[0];$source=Request @('identify')
 $entry=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'usage' -and $_.layout_visible});Require ($entry.Count -eq 1) 'AI Usage footer entry missing';Require ([OptionsFixture]::Text([long]$entry[0].handle,$owned.Id) -match 'AI [Uu]sage') 'AI Usage accessible button caption missing';Click ([long]$entry[0].handle)
 $tree=Await {param($t) $t.usage.panel.open -and $t.usage.state.refreshing -and $t.usage.worker_active};$panel=Panel $tree;Require (-not [OptionsFixture]::Describe([long]$panel.refresh,$owned.Id).Enabled) 'Refresh remained enabled while collection is in flight';Paint $tree $false
 1..3|ForEach-Object {[PaneToolsFixture]::Command($owned,[long]$panel.window,[long]$panel.refresh)};$tree=Tree;Require ($tree.usage.worker_active -and $tree.usage.state.refreshing) 'Repeated pending refresh ended the in-flight request';Passed 'footer-opens-owned-360DIP-popover-and-busy-refresh-is-disabled-coalesced'

 $scope='한글 한 é 😀';$reset=[DateTime]::UtcNow.AddHours(4).ToString('o');$epoch=[DateTimeOffset]::UtcNow.AddHours(4).ToUnixTimeSeconds();$day=[DateTime]::Now.ToString('yyyy-MM-dd')
 $sample=@{claude=@{today=12345;limits=@{five_hour=@{utilization=37;resets_at=$reset};seven_day=@{utilization=63;resets_at=$reset}}};codex=@{tokens=@{result=@{summary=@{lifetimeTokens=987654};dailyUsageBuckets=@(@{startDate=$day;tokens=3210})}};limits=@{result=@{rateLimits=@{limitId='codex';limitName=$scope;primary=@{usedPercent=24;windowDurationMins=300;resetsAt=$epoch};secondary=@{usedPercent=48;windowDurationMins=10080;resetsAt=$epoch}}}}}}
 $tree=Inject $sample;$panel=Panel $tree;Require ($tree.usage.state.claude.tokens.value.today -eq 12345 -and $tree.usage.state.codex.tokens.value.today -eq 3210 -and $tree.usage.state.codex.tokens.value.lifetime -eq 987654) 'Parsed real provider token DTO values differ'
 Require ($panel.cards[0].text.Contains('Tokens today 12.3K') -and $panel.cards[1].text.Contains('Lifetime tokens 987.7K') -and $panel.cards[1].text.Contains($scope) -and $panel.cards[0].text.Contains('Resets at')) 'Native token/scope/reset text missing or Unicode normalized'
 $viewport=[ChromeFixture]::Size([long]$panel.viewport,$owned.Id);$scale=[OptionsFixture]::Describe([long]$panel.window,$owned.Id).Dpi/96.0;Require ($viewport[1] -ge 180*$scale-3 -and $viewport[1] -le 520*$scale+3) 'Usage viewport is outside180..520DIP';$anchor=@($tree.chrome.controls|Where-Object {$_.handle -eq $panel.anchor})[0];$anchorBounds=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$anchor.handle,$owned.Id);$popupRelative=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$panel.window,$owned.Id)
 Require ($popupRelative.Y+$popupRelative.Height -le $anchorBounds.Y) 'Usage popup was not placed above its footer anchor'
 Paint $tree;Bar-Paint $tree;Require (@($tree.usage.bar.meters).Count -eq 4) 'Persistent usage bar did not resolve both periods/providers';Passed 'real-domain-parsers-native-Unicode-cards-limits-and-production-meter-pixels'

 $mainSize=[ChromeFixture]::Size([long]$tree.window_handle,$owned.Id);$barWindow=$tree.usage.bar.window;$barControl=$tree.usage.bar.control
 foreach($width in @(800,420)){[ChromeFixture]::Resize([long]$tree.window_handle,$owned.Id,$width,$mainSize[1]);$tree=Tree;Bar-Paint $tree $true;Stable $tree;Require ($tree.usage.bar.window -eq $barWindow -and $tree.usage.bar.control -eq $barControl) 'Usage resize recreated its controls'}
 [ChromeFixture]::Resize([long]$tree.window_handle,$owned.Id,$mainSize[0],$mainSize[1]);$tree=Tree;Bar-Paint $tree
 # Set the real checkbox state before its owned BN_CLICKED notification; no BM_CLICK or focus.
 $withBar=Pane-Height $tree;[OptionsFixture]::SetChecked([long]$panel.window,[long]$panel.toggle,$owned.Id,$false);Click ([long]$panel.toggle);$tree=Await {param($t) -not $t.usage.bar.enabled};$withoutBar=Pane-Height $tree;Require ($withoutBar -gt $withBar) 'Hiding usage bar did not return height to pane';Paint $tree $false
 $config=Get-Content -Raw -LiteralPath (Join-Path $directory 'config\config.json')|ConvertFrom-Json;Require ($config.terminal.usage_bar_enabled -eq $false) 'Hide bar toggle was not persisted';[OptionsFixture]::SetChecked([long]$tree.usage.panel.window,[long]$tree.usage.panel.toggle,$owned.Id,$true);Click ([long]$tree.usage.panel.toggle);$tree=Await {param($t) $t.usage.bar.enabled};Require ((Pane-Height $tree) -eq $withBar) 'Showing usage bar did not restore pane height';$relative=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$tree.usage.bar.window,$owned.Id);$client=[ChromeFixture]::Size([long]$tree.window_handle,$owned.Id);Require ($relative.Y+$relative.Height -le $client[1] -and $relative.Y -ge $tree.layout.panes[0][1].y+$tree.layout.panes[0][1].height) 'Usage bar overlaps pane content';Passed 'Show-bar-persists-config-and-reserves-main-content-bottom-without-replacing-terminal'

 $claudeBefore=$tree.usage.state.claude;$stale=@{claude=@{token_error=$true;limits_error=$true};codex=$sample.codex};Click ([long]$tree.usage.panel.refresh);$tree=Await {param($t) $t.usage.worker_active};$tree=Inject $stale
 Require ($tree.usage.state.claude.tokens.value.today -eq 12345 -and $tree.usage.state.claude.tokens.updated_at -ceq $claudeBefore.tokens.updated_at -and $tree.usage.state.claude.limits.updated_at -ceq $claudeBefore.limits.updated_at -and $tree.usage.state.claude.limits.value[0].used_percent -eq $claudeBefore.limits.value[0].used_percent) 'Failed provider refresh discarded retained fields/timestamps'
 Require ($tree.usage.panel.cards[0].text.Contains('Token data last updated') -and $tree.usage.panel.cards[0].text.Contains('Rate limits last updated') -and $tree.usage.panel.cards[0].text.Contains('Usage service unavailable.') -and -not $tree.usage.state.codex.token_error -and -not $tree.usage.state.codex.limits_error -and @($tree.usage.bar.meters|Where-Object {$_.stale}).Count -eq 2) 'Partial provider failure lost stale markers or contaminated healthy provider';Bar-Paint $tree;Passed 'partial-failure-retains-last-known-fields-and-bar-while-other-provider-succeeds'

 $many=@();1..12|ForEach-Object {$many+=@{kind='weekly';group=($scope+' '+$_);utilization=$_;resets_at=$reset}};$long=@{claude=@{today=12345;limits=@{five_hour=@{utilization=37;resets_at=$reset};limits=$many}};codex=$sample.codex};$tree=Inject $long;$panel=Panel $tree;[OptionsFixture]::Scroll([long]$panel.viewport,$owned.Id,$true);$tree=Await {param($t) $t.usage.panel.scroll_offset -gt 0};$viewport=[ChromeFixture]::Size([long]$tree.usage.panel.viewport,$owned.Id);Require ($viewport[1] -le 520*$scale+3) 'Large usage response grew unbounded popup';[OptionsFixture]::Scroll([long]$panel.viewport,$owned.Id,$false);$tree=Await {param($t) $t.usage.panel.scroll_offset -eq 0};$tree=Inject $sample;Passed 'large-provider-card-scrolls-within520DIP-and-restores-top'

 $tree=Close-Popup $tree;Shortcut;$tree=Await {param($t) $t.usage.panel.open};Panel $tree|Out-Null;$tree=Close-Popup $tree;Passed 'CtrlAltU-production-renderer-opens-and-owned-Escape-closes-without-desktop-input'

 $button=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'command_palette' -and $_.layout_visible})[0];Click ([long]$button.handle);$tree=Await {param($t) $t.command_palette.open};$palette=$tree.command_palette;[OptionsFixture]::SetTextAndNotify([long]$palette.window,[long]$palette.query_handle,$owned.Id,'AI usage');$tree=Await {param($t) @($t.command_palette.filtered) -ccontains 'action:toggle-usage-popover'};$palette=$tree.command_palette;$index=[Array]::IndexOf(@($palette.filtered),'action:toggle-usage-popover');$current=[int]$palette.selected_index;$key=if($current -gt $index){38}else{40};for($i=0;$i -lt [Math]::Abs($index-$current);$i++){[OptionsFixture]::PostKey([long]$palette.query_handle,$owned.Id,$key,$false,$false);[OptionsFixture]::PostKey([long]$palette.query_handle,$owned.Id,$key,$true,$false)};$tree=Await {param($t) $t.command_palette.selected -ceq 'action:toggle-usage-popover'};[OptionsFixture]::PostEnter([long]$tree.command_palette.query_handle,$owned.Id);$tree=Await {param($t) $t.usage.panel.open -and -not $t.command_palette.open};Passed 'Command-Palette-AI-usage-invokes-the-same-owned-popover'

 $window=$tree.usage.panel.window;$cards=@($tree.usage.panel.cards.window);Request @('settings','set','theme-preset','nord')|Out-Null;$tree=Await {param($t) $t.usage.panel.colors.surface -ne $panel.colors.surface};Require ($tree.usage.panel.window -eq $window -and (@($tree.usage.panel.cards.window)-join ',') -ceq ($cards-join ',')) 'Theme update recreated usage controls';Paint $tree;Bar-Paint $tree;$tree=Close-Popup $tree;Passed 'theme-updates-existing-native-cards-and-production-paint-without-session-change'

 Shortcut;$tree=Await {param($t) $t.usage.panel.open};Panel $tree|Out-Null;Request @('new-tab','--shell=cmd')|Out-Null
 $tree=Await {param($t) @($t.surfaces).Count -eq 2 -and -not $t.usage.panel.open -and $t.usage.panel.anchor -eq 0};$extra=@($tree.surfaces|Where-Object {$_.id -cne $original.id});Require ($extra.Count -eq 1) 'Control rebuild created unexpected terminals'
 Request @('close-tab',$extra[0].id)|Out-Null;Request @('focus-tab',$source.surface)|Out-Null;$tree=Await {param($t) @($t.surfaces).Count -eq 1};Shortcut;$tree=Await {param($t) $t.usage.panel.open};$panel=Panel $tree
 $newAnchor=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'usage' -and $_.layout_visible});Require ($newAnchor.Count -eq 1 -and $panel.anchor -eq $newAnchor[0].handle) 'Reopened Usage retained a destroyed control anchor'
 $anchorBounds=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$newAnchor[0].handle,$owned.Id);$popupBounds=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$panel.window,$owned.Id);Require ($popupBounds.Y+$popupBounds.Height -le $anchorBounds.Y) 'Reopened Usage no longer appears above its new footer anchor';$tree=Close-Popup $tree;Passed 'control-rebuild-closes-popover-clears-anchor-and-reopen-uses-current-footer'

 Request @('detach-tab',$source.surface)|Out-Null;$tree=Await {param($t) @($t.detached_windows).Count -eq 1 -and @($t.layout.panes).Count -eq 0};$detached=$tree.detached_windows[0];Require ($detached.surface -ceq $source.surface -and -not $detached.native_visible -and -not $tree.main_closed) 'Original terminal was not detached into an owned hidden window'
 $entry=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'usage' -and $_.layout_visible});Require ($entry.Count -eq 1) 'Empty main lost AI Usage footer';Click ([long]$entry[0].handle);$tree=Await {param($t) $t.usage.panel.open};$panel=Panel $tree;Click ([long]$panel.refresh);$tree=Await {param($t) $t.usage.worker_active -and $t.usage.state.refreshing};$oldPanel=[long]$tree.usage.panel.window;$oldBar=[long]$tree.usage.bar.window;$retiredJob=$tree.usage.job_id
 [FindFixture]::PostClose([long]$tree.window_handle,$owned.Id);$tree=Await {param($t) $t.main_closed -and -not $t.state.saving -and $null -eq $t.usage.panel -and $null -eq $t.usage.bar -and -not $t.usage.worker_active -and -not $t.usage.state.refreshing -and $t.usage.retry -eq 0}
 Require ([OptionsFixture]::WindowDestroyed($oldPanel) -and [OptionsFixture]::WindowDestroyed($oldBar)) 'Closing main left Usage native windows alive';Require (@($tree.detached_windows).Count -eq 1 -and $tree.detached_windows[0].window_handle -eq $detached.window_handle -and $tree.surfaces[0].holder.parent -eq $detached.window_handle) 'Main close removed or reparented detached terminal'
 $finalState=$tree.usage.state|ConvertTo-Json -Depth 30 -Compress;$late=$sample.Clone();$late.claude=$sample.claude.Clone();$late.claude.today=7654321;Request @('test-usage',($late|ConvertTo-Json -Depth 30 -Compress))|Out-Null;$tree=Tree
 Require (($tree.usage.state|ConvertTo-Json -Depth 30 -Compress) -ceq $finalState -and $null -eq $tree.usage.panel -and $null -eq $tree.usage.bar -and -not $tree.usage.worker_active -and -not $tree.usage.state.refreshing -and $tree.usage.retry -eq 0) 'Late Usage result changed state or restarted collection after main close';Passed 'main-close-destroys-Usage-cancels-pending-refresh-ignores-late-result-and-retains-detached-PTY'

 Request @('new-workspace','--cwd',$directory,'--shell=cmd')|Out-Null
 $tree=Await {param($t) -not $t.main_closed -and @($t.surfaces).Count -eq 2 -and $t.usage.bar.window -and @($t.usage.bar.meters).Count -eq 4 -and @($t.surfaces|Where-Object {$_.id -cne $original.id -and $_.ready -and $_.running}).Count -eq 1};$reopened=Request @('identify')
 $preserved=@($tree.surfaces|Where-Object {$_.id -ceq $original.id})[0];Require ($preserved.pid -eq $original.pid -and $preserved.session -ceq $original.session -and $preserved.view_handle -eq $original.view_handle -and $preserved.holder.window -eq $original.holder.window -and $preserved.holder.parent -eq $detached.window_handle -and $preserved.running) 'Main reopen replaced or reparented the surviving detached terminal'
 Require (@($tree.detached_windows).Count -eq 1 -and $tree.detached_windows[0].window_handle -eq $detached.window_handle -and -not $tree.detached_windows[0].native_visible) 'Main reopen replaced or showed the detached frame'
 Require (($tree.usage.state|ConvertTo-Json -Depth 30 -Compress) -ceq $finalState -and -not $tree.usage.worker_active -and $tree.usage.bar.enabled) 'Main reopen lost retained usage data or started account collection'
 $barBounds=[OptionsFixture]::RelativeBounds([long]$tree.window_handle,[long]$tree.usage.bar.window,$owned.Id);$mainPane=@($tree.layout.panes|Where-Object {$_[0] -ceq $reopened.pane});Require ($mainPane.Count -eq 1 -and $barBounds.Height -gt 0 -and $barBounds.Y -ge $mainPane[0][1].y+$mainPane[0][1].height -and -not [CliProbe]::IsWindowVisible([IntPtr][long]$tree.usage.bar.window)) 'Restored usage bar did not reserve hidden main content height'
 $entry=@($tree.chrome.controls|Where-Object {$_.kind -ceq 'usage' -and $_.layout_visible});Require ($entry.Count -eq 1) 'Reopened main lost Usage footer';Click ([long]$entry[0].handle);$tree=Await {param($t) $t.usage.panel.open};$panel=Panel $tree;Click ([long]$panel.refresh);$tree=Await {param($t) $t.usage.worker_active -and $t.usage.state.refreshing -and $t.usage.job_id};$currentJob=$tree.usage.job_id
 Require ($retiredJob -and $currentJob -cne $retiredJob) 'Reopened refresh reused the cancelled collector identity';$inflightState=$tree.usage.state|ConvertTo-Json -Depth 30 -Compress;$late.job_id=$retiredJob;Request @('test-usage',($late|ConvertTo-Json -Depth 30 -Compress))|Out-Null;$tree=Tree
 Require ($tree.usage.job_id -ceq $currentJob -and $tree.usage.worker_active -and $tree.usage.state.refreshing -and ($tree.usage.state|ConvertTo-Json -Depth 30 -Compress) -ceq $inflightState) 'Retired collector changed reopened state or consumed the current refresh'
 $completed=$sample.Clone();$completed.job_id=$currentJob;$tree=Inject $completed;Require ($tree.usage.state.claude.tokens.value.today -eq 12345 -and @($tree.usage.bar.meters).Count -eq 4) 'Current reopened refresh did not update the restored bar';$tree=Close-Popup $tree
 Request @('workspace','close',$reopened.workspace)|Out-Null;$tree=Await {param($t) @($t.surfaces).Count -eq 1 -and -not $t.main_closed -and $t.usage.bar.window};Passed 'main-reopen-restores-usage-bar-popover-and-retained-data-while-retired-job-cannot-consume-new-refresh'
}
catch{$failure=$_.Exception.Message}
finally{
 $cleaning=$true
 if($owned){try{if(-not $owned.HasExited){Request @('quit','--discard-state')|Out-Null;Require ($owned.WaitForExit(4000)) 'Owned host quit timed out'};Require ($owned.ExitCode -eq 0) 'Owned host failed'}catch{$cleanupErrors+=,$_.Exception.Message}finally{try{if(-not $owned.HasExited){$owned.Kill();[CliProbe]::WaitAfterKill($owned)};$diagnostic.host=@{pid=$owned.Id;exitCode=$owned.ExitCode;stdout=[CliProbe]::Output($hostOut);stderr=[CliProbe]::Output($hostErr)}}catch{$cleanupErrors+=,$_.Exception.Message}finally{$owned.Dispose()}}}
 $env:LOCALAPPDATA=$savedLocal
}
if($failure -or $cleanupErrors.Count){$diagnostic.failure=$failure;$diagnostic.cleanupErrors=$cleanupErrors;$diagnostic.elapsedMs=$clock.ElapsedMilliseconds;$diagnostic|ConvertTo-Json -Depth 60|Set-Content -Encoding UTF8 -LiteralPath (Join-Path $directory 'failure.json');throw ($failure+' '+($cleanupErrors -join '; '))}
Write-Output ('passed: '+$checks.Count+' hidden usage groups; elapsed='+$clock.ElapsedMilliseconds+'ms')
