// SPDX-License-Identifier: GPL-3.0-or-later
//! Twelve office concepts. Each differs in value structure and materials, not only hue.

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Floor {
    Herringbone,
    Tiles,
    Grid,
    Carpet,
    Concrete,
    Checker,
    Planks,
    Tatami,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Wall {
    Plaster,
    Glass,
    Panels,
    Brick,
    Stripes,
    Logs,
    Shoji,
    Metal,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum View {
    City,
    Garden,
    NightCity,
    Space,
    Snow,
    Sea,
    Bamboo,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum DeskStyle {
    Wood,
    White,
    Metal,
    Low,
}

/// Large standing pieces that give a room its focal point.
#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Feature {
    Easel,
    Bookcase,
    Planter,
    PottingBench,
    ServerRack,
    Telescope,
    Globe,
    Workbench,
    Printer3d,
    EspressoBar,
    PastryCase,
    Arcade,
    Vending,
    HydroPod,
    Console,
    Fireplace,
    WoodPile,
    SurfRack,
    DeckChair,
    Bonsai,
    StoneLantern,
    Gumball,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Decor {
    Pinboard,
    Frame,
    HangingPlants,
    Shelf,
    MonitorWall,
    StarChart,
    Pegboard,
    Poster,
    Chalkboard,
    Bunting,
    Neon,
    Porthole,
    Skis,
    Lifebuoy,
    Scroll,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Clutter {
    FloorLamp,
    Crates,
    WateringCan,
    SmallPot,
    Bin,
    BookPile,
    Stool,
    LavaLamp,
    BeanBag,
    Cushion,
    PaperLantern,
}

#[derive(Clone, Copy, Debug, Hash, PartialEq, Eq)]
pub(super) enum Plant {
    Monstera,
    Fern,
    Palm,
    Snake,
    Cactus,
    Fir,
    Bamboo,
}

pub(super) struct Theme {
    pub name: &'static str,
    pub layouts: [&'static str; 4],
    pub floor: Floor,
    pub floor_colors: (u32, u32),
    pub wall: Wall,
    pub wall_colors: (u32, u32),
    pub trim: u32,
    pub wood: u32,
    pub fabric: u32,
    pub accent: u32,
    pub accent2: u32,
    pub rug: (u32, u32),
    pub view: View,
    pub desk: DeskStyle,
    pub features: [Feature; 2],
    pub decor: [Decor; 2],
    pub clutter: [Clutter; 2],
    pub plants: [Plant; 2],
    /// Dark rooms add warm light pools and glowing screens.
    pub dark: bool,
}

pub(super) const THEMES: [Theme; 12] = [
    Theme {
        name: "Daylight atelier",
        layouts: [
            "Window desks",
            "Studio pods",
            "Long worktable",
            "Corner clusters",
        ],
        floor: Floor::Herringbone,
        floor_colors: (0xdcbb8b, 0xc9a477),
        wall: Wall::Plaster,
        wall_colors: (0xf3e8d3, 0xd6c3a2),
        trim: 0x9a7451,
        wood: 0xc99260,
        fabric: 0x5f927f,
        accent: 0xe2725b,
        accent2: 0x4f7fb0,
        rug: (0xeedcb8, 0xc9704f),
        view: View::City,
        desk: DeskStyle::Wood,
        features: [Feature::Easel, Feature::Bookcase],
        decor: [Decor::Pinboard, Decor::Frame],
        clutter: [Clutter::FloorLamp, Clutter::Crates],
        plants: [Plant::Monstera, Plant::Fern],
        dark: false,
    },
    Theme {
        name: "Fern conservatory",
        layouts: [
            "Growing aisle",
            "Glass court",
            "Seed library",
            "Canopy desks",
        ],
        floor: Floor::Tiles,
        floor_colors: (0xcf9468, 0xbd8159),
        wall: Wall::Glass,
        wall_colors: (0xb5d8c8, 0x4d6b5b),
        trim: 0x4d6b5b,
        wood: 0xeae4d2,
        fabric: 0xd8a650,
        accent: 0x6aa84f,
        accent2: 0xe7795f,
        rug: (0xece0c2, 0x7fa66b),
        view: View::Garden,
        desk: DeskStyle::White,
        features: [Feature::Planter, Feature::PottingBench],
        decor: [Decor::HangingPlants, Decor::Shelf],
        clutter: [Clutter::WateringCan, Clutter::SmallPot],
        plants: [Plant::Fern, Plant::Palm],
        dark: false,
    },
    Theme {
        name: "Signal observatory",
        layouts: [
            "Signal bays",
            "Paired consoles",
            "Observation deck",
            "Relay room",
        ],
        floor: Floor::Grid,
        floor_colors: (0x2c3b55, 0x25324a),
        wall: Wall::Metal,
        wall_colors: (0x1e2a42, 0x2a3a5e),
        trim: 0x5d7ca8,
        wood: 0x4b5f82,
        fabric: 0x3f6fb5,
        accent: 0x5fe0d0,
        accent2: 0xf2b450,
        rug: (0x33476d, 0x5fe0d0),
        view: View::NightCity,
        desk: DeskStyle::Metal,
        features: [Feature::ServerRack, Feature::Telescope],
        decor: [Decor::MonitorWall, Decor::StarChart],
        clutter: [Clutter::Crates, Clutter::Bin],
        plants: [Plant::Snake, Plant::Fern],
        dark: true,
    },
    Theme {
        name: "Folio library",
        layouts: [
            "Archive lane",
            "Reading court",
            "Quiet alcoves",
            "Study pairs",
        ],
        floor: Floor::Carpet,
        floor_colors: (0x7d3e42, 0x70363a),
        wall: Wall::Panels,
        wall_colors: (0x5e3c2b, 0x734c36),
        trim: 0x3e271c,
        wood: 0x80523a,
        fabric: 0x3f6b4f,
        accent: 0xe0b54f,
        accent2: 0xb5473f,
        rug: (0x2f4f43, 0xe0b54f),
        view: View::Garden,
        desk: DeskStyle::Wood,
        features: [Feature::Bookcase, Feature::Globe],
        decor: [Decor::Shelf, Decor::Frame],
        clutter: [Clutter::BookPile, Clutter::FloorLamp],
        plants: [Plant::Fern, Plant::Monstera],
        dark: true,
    },
    Theme {
        name: "Copper workshop",
        layouts: [
            "Assembly line",
            "Tool island",
            "Twin benches",
            "Material wall",
        ],
        floor: Floor::Concrete,
        floor_colors: (0x9c9a94, 0x908e88),
        wall: Wall::Brick,
        wall_colors: (0xa95c44, 0xcdbba6),
        trim: 0x4b4f55,
        wood: 0xc0905f,
        fabric: 0x4d6e8a,
        accent: 0xe8873a,
        accent2: 0xf1c84b,
        rug: (0x5d6670, 0xe8873a),
        view: View::City,
        desk: DeskStyle::Metal,
        features: [Feature::Workbench, Feature::Printer3d],
        decor: [Decor::Pegboard, Decor::Poster],
        clutter: [Clutter::Crates, Clutter::Stool],
        plants: [Plant::Cactus, Plant::Snake],
        dark: false,
    },
    Theme {
        name: "Tea commons",
        layouts: [
            "Counter seats",
            "Corner gathering",
            "Morning tables",
            "Evening commons",
        ],
        floor: Floor::Checker,
        floor_colors: (0xf0e3c8, 0xbb7c5d),
        wall: Wall::Stripes,
        wall_colors: (0xf6ebd7, 0xe9c9a0),
        trim: 0x8a5a3c,
        wood: 0xab7049,
        fabric: 0xd98c8c,
        accent: 0x6fae9b,
        accent2: 0xe0a74a,
        rug: (0xf3e3c3, 0xd98c8c),
        view: View::City,
        desk: DeskStyle::Wood,
        features: [Feature::EspressoBar, Feature::PastryCase],
        decor: [Decor::Chalkboard, Decor::Bunting],
        clutter: [Clutter::Stool, Clutter::SmallPot],
        plants: [Plant::Monstera, Plant::Palm],
        dark: false,
    },
    Theme {
        name: "Neon night shift",
        layouts: [
            "Night rows",
            "Glow pods",
            "Midnight bench",
            "Arcade corners",
        ],
        floor: Floor::Planks,
        floor_colors: (0x2b2243, 0x241c39),
        wall: Wall::Metal,
        wall_colors: (0x1b1531, 0x2c2352),
        trim: 0xff5fa2,
        wood: 0x3d3163,
        fabric: 0x6b4fd8,
        accent: 0xff5fa2,
        accent2: 0x45e3ff,
        rug: (0x352b5a, 0xff5fa2),
        view: View::NightCity,
        desk: DeskStyle::Metal,
        features: [Feature::Arcade, Feature::Vending],
        decor: [Decor::Neon, Decor::Poster],
        clutter: [Clutter::LavaLamp, Clutter::BeanBag],
        plants: [Plant::Snake, Plant::Cactus],
        dark: true,
    },
    Theme {
        name: "Orbital station",
        layouts: ["Docking row", "Crew pods", "Command bench", "Habitat ring"],
        floor: Floor::Grid,
        floor_colors: (0xcad2db, 0xb9c2cd),
        wall: Wall::Metal,
        wall_colors: (0xe6ebf1, 0xcfd7e1),
        trim: 0x5c6b80,
        wood: 0xf2f4f7,
        fabric: 0x4f86c6,
        accent: 0xff8a3d,
        accent2: 0x52d1a0,
        rug: (0xa3b3c6, 0x4f86c6),
        view: View::Space,
        desk: DeskStyle::White,
        features: [Feature::HydroPod, Feature::Console],
        decor: [Decor::Porthole, Decor::MonitorWall],
        clutter: [Clutter::Crates, Clutter::Bin],
        plants: [Plant::Fern, Plant::Snake],
        dark: false,
    },
    Theme {
        name: "Alpine lodge",
        layouts: ["Hearth rows", "Cabin pods", "Long table", "Snowed-in nooks"],
        floor: Floor::Planks,
        floor_colors: (0xab774c, 0x9a6842),
        wall: Wall::Logs,
        wall_colors: (0x8c5a36, 0x75492b),
        trim: 0x4e3220,
        wood: 0x9e6c43,
        fabric: 0xb5413c,
        accent: 0xf0c060,
        accent2: 0x3f6f58,
        rug: (0xb5413c, 0x2f3d55),
        view: View::Snow,
        desk: DeskStyle::Wood,
        features: [Feature::Fireplace, Feature::WoodPile],
        decor: [Decor::Skis, Decor::Frame],
        clutter: [Clutter::Stool, Clutter::FloorLamp],
        plants: [Plant::Fir, Plant::Fern],
        dark: false,
    },
    Theme {
        name: "Seaside studio",
        layouts: ["Boardwalk desks", "Tide pods", "Pier table", "Cove corners"],
        floor: Floor::Planks,
        floor_colors: (0xece7dd, 0xdcd5c7),
        wall: Wall::Stripes,
        wall_colors: (0xf8f7f2, 0x75abcb),
        trim: 0x3d6e94,
        wood: 0xdcc6a2,
        fabric: 0x5d9ec7,
        accent: 0xf08a5d,
        accent2: 0xf3cf6a,
        rug: (0x75abcb, 0xf8f7f2),
        view: View::Sea,
        desk: DeskStyle::White,
        features: [Feature::SurfRack, Feature::DeckChair],
        decor: [Decor::Lifebuoy, Decor::Shelf],
        clutter: [Clutter::BeanBag, Clutter::SmallPot],
        plants: [Plant::Palm, Plant::Cactus],
        dark: false,
    },
    Theme {
        name: "Zen tatami",
        layouts: ["Garden rows", "Tea pods", "Low table", "Moss corners"],
        floor: Floor::Tatami,
        floor_colors: (0xcbc690, 0xbab47f),
        wall: Wall::Shoji,
        wall_colors: (0xf3ecd8, 0x8c6a48),
        trim: 0x5a4232,
        wood: 0x8c6a48,
        fabric: 0x6d7f5c,
        accent: 0xc7473f,
        accent2: 0x3f5f7f,
        rug: (0x3f5f7f, 0xe8dfc6),
        view: View::Bamboo,
        desk: DeskStyle::Low,
        features: [Feature::Bonsai, Feature::StoneLantern],
        decor: [Decor::Scroll, Decor::HangingPlants],
        clutter: [Clutter::Cushion, Clutter::PaperLantern],
        plants: [Plant::Bamboo, Plant::Fern],
        dark: false,
    },
    Theme {
        name: "Pop arcade loft",
        layouts: ["Candy rows", "Bubble pods", "Pixel bench", "Bonus corners"],
        floor: Floor::Checker,
        floor_colors: (0xfdf0f6, 0xf3bfd8),
        wall: Wall::Stripes,
        wall_colors: (0xc4e8f4, 0xa6dbee),
        trim: 0x7a5bd1,
        wood: 0xf5f2fb,
        fabric: 0xffb84d,
        accent: 0xff6fb5,
        accent2: 0x6fd6ff,
        rug: (0x7a5bd1, 0xffd84d),
        view: View::City,
        desk: DeskStyle::White,
        features: [Feature::Arcade, Feature::Gumball],
        decor: [Decor::Neon, Decor::Bunting],
        clutter: [Clutter::BeanBag, Clutter::Cushion],
        plants: [Plant::Cactus, Plant::Monstera],
        dark: false,
    },
];

pub(super) const LAYOUTS: usize = 4;
pub(super) const DESIGNS: usize = THEMES.len() * LAYOUTS;

pub(super) fn theme(design: usize) -> &'static Theme {
    &THEMES[design % DESIGNS / LAYOUTS]
}

pub(super) fn design_name(design: usize) -> String {
    let theme = theme(design);
    format!("{} / {}", theme.name, theme.layouts[design % LAYOUTS])
}
