#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate one distribution notice; share identical terms without losing credits."""

import json
from pathlib import Path
import re
import subprocess


def group_licenses(licenses):
    groups = {}
    for license in licenses:
        text = license["text"].strip()
        # Keep every prefix and suffix. Unknown license formats stay intact.
        marker = {"MIT": "Permission is hereby granted", "ISC": "Permission to use"}.get(
            license["id"], ""
        )
        prefix, terms = "", text
        if marker and marker in text:
            prefix, rest = text.split(marker, 1)
            terms = marker + rest
        key = (license["id"], " ".join(terms.split()))
        group = groups.setdefault(key, {"name": license["name"], "terms": terms, "credits": {}})
        credits = group["credits"].setdefault(prefix.strip(), set())
        credits.update(f'{entry["crate"]["name"]} {entry["crate"]["version"]}' for entry in license["used_by"])
    return groups.values()


def block(text):
    fence = "~" * max(4, 1 + max((len(run) for run in re.findall(r"~+", text)), default=0))
    return f"{fence}text\n{text}\n{fence}"


def render(licenses):
    sections = []
    for group in group_licenses(licenses):
        sections.append(f'### {group["name"]}')
        for notice, crates in group["credits"].items():
            sections.append("Used by: " + ", ".join(sorted(crates)))
            if notice:
                sections.append(block(notice))
        sections.append(block(group["terms"]))
    return "\n\n".join(sections)


def main():
    root = Path(__file__).resolve().parent.parent
    inventory = json.loads(subprocess.check_output([
        "cargo", "about", "generate", "--config", "packaging/licenses/about.toml",
        "--workspace", "--locked", "--fail", "--format", "json",
    ], cwd=root))
    credits = (root / "docs/legal/THIRD_PARTY_NOTICES.md").read_text()
    monaco = (root / "editor/flowmux-editor-web/MONACO_THIRD_PARTY_NOTICES.txt").read_text()
    output = (
        "<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n\n"
        "# Third-Party Licenses\n\n"
        "Generated by `scripts/generate-third-party-licenses.py` from production/build "
        "dependencies in Cargo.lock and bundled asset/editor notices. Identical terms are shared; "
        "the credits above each text identify the components they cover.\n\n"
        + credits + "\n## Rust dependencies\n\n" + render(inventory["licenses"])
        + "\n\n## Monaco upstream component notices\n\n" + block(monaco) + "\n"
    )
    destination = root / "docs/legal/THIRD_PARTY_LICENSES.md"
    destination.write_text("\n".join(line.rstrip() for line in output.splitlines()).rstrip() + "\n")
    print(f"Refreshed {destination.relative_to(root)}")


if __name__ == "__main__":
    main()
